### ISSUE TITLE
Intergration with NEI partly missing?

### ISSUE THREAD

**Issue by MoonCutter2B** [lumien231/Random-Things#10]
Also found the following error in forge 1480 log:

[12:41:48] [Client thread/ERROR] [NotEnoughItems/]: Missing container for randomthings

**Comment by lumien231** [comment]
What do you mean? What is not working?

**Comment by MoonCutter2B** [comment]
Its a error message from Forge - I'm not sure if it significant or not.
Since I wrote the issue I'v learnt that some of the errors in the log isn't real errors.
I have 25+ add-ons loaded and the message is only logged for two add-ons.

Next time I play I will check if NEI actually have a problem or not.
(I did get a crash opening the achievement panel, not sure what add-on though).
