### ISSUE TITLE
Random things world wont load

### ISSUE THREAD

**Issue by abdullamu** [lumien231/Random-Things#101]
hello 
when i add random things to my mods and start minecraft it loads fine without crash but when i try to load map or start new one nothing happen i get sent back to main menu but it crashes in the log

the last lines show the crash after world load but the game doesnt just i get sent back to menu

**Comment by lumien231** [comment]
Looks like a dimension id conflict of some sort, try to set the spectre dimension id to something like 56 in the config file.

**Comment by abdullamu** [comment]
yup figured out that after going through the crash changed that to 50, i suggest u change the id for the dimension for other users who doesnt know that.

**Comment by lumien231** [comment]
When you first download the mod the dimension id is set to -1 which causes random things to auto resolve it and find a free id. I don't actually know how this conflict happened.
