### ISSUE TITLE
Entity Detector

### ISSUE THREAD

**Issue by Lagosaurus** [lumien231/Random-Things#103]
I realize that you're no longer supporting the 1.7.10 version but I've had several players on my server request support for the entity detector. I noticed that there isn't a 1.7 branch and was wondering if the 1.7 source code is available somewhere. I would like to at least attempt to implement the entity detector for 1.7.10.

**Comment by lumien231** [comment]
The 1.7.10 source code is not available anymore :/. Maybe just make your own small mod or something.
