### ISSUE TITLE
1.10.2 crash on latest forge 2027

### ISSUE THREAD

**Issue by tgstyle** [lumien231/Random-Things#106]
https://gist.github.com/tgstyle/fa3986c9e0496885f03eda5b1ab75bcd

**Comment by lumien231** [comment]
Works fine for on 2052, can you reproduce it there? If so, how?

**Comment by tgstyle** [comment]
2045 did this.

LexManos:
        Restone binary compatibility with registry substitution rework. Modders
        please switch to using the provided RegistryBuilder to ensure more
        forward compatbility. Closes #3144

This seems to have provided the work around, however it seems there still may be an underlying issue.
