### ISSUE TITLE
CTD on startup

### ISSUE THREAD

**Issue by TheLittleArtist** [lumien231/Random-Things#106]
Added random things and updated COFH mods to FTB infinity 1.2.0 
Booted fine with just the COFH updates, started crashing to desktop with no crash log and the below pastebin outputted to FML-Client-Latest.
Seems to be some sort of error with leaf decay, possibly a conflict with the fast leaf decay mod included in infinity? I don't know enough to call that for sure though. Tried booting with that disabled but same error.

Minecraft version 1.7.10
Java version 7 update 75
64 bit OS
4Gb ram
8-core AMD FX series at 4.9Ghz

FML-Client Log: http://pastebin.com/BrN6Jj1k

**Comment by lumien231** [comment]
Yes of course it's a conflict with the fast leave decay included in infinity, that mod is just a part of the fast leave decay code from random things so they are not compatible with each other.

**Comment by TheLittleArtist** [comment]
Ah my bad, realised i messed up disabling the leaf decay mod, thanks for the speedy response, i'm an idiot.
Great work on the mod by the way, i know you guys don't always get the best responses from the community, but really great work, I struggle to play without your mod anymore. from an internet stranger, have a nice day o/

**Comment by AtomicTim** [comment]
Almost submitted an issue but found this...was worried I would have to play without Random Things :O
