### ISSUE TITLE
Missing config file and commands in RT Minecraft 1.8

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [lumien231/Random-Things#109]
I am using the new Minecraft 1.8 Random Things Mod after testing it first in 1.7.10. After performing a fresh install of Forge and Random Things (RT), the mod didn't generate a config file. This is true when I try to run a Forge client, or a Forge Server. So far, the blocks seem to be OK, but I can't do the /rt bloodmoon command. When i type in the command and hit enter, nothing happens. I checked the server logs, but it didn't even say anything about me doing a command. I don't know if this is part of the issue, or just something else, but the items (spectre key, bloodstone, etc.) don't show up in the creative inventory. Any help would be much appreciated! Thank you

Major General Relativity

**Comment by MajorGeneralRelativity** [comment]
Oh, if it helps, I followed the download link and downloaded RandomThings-MC1.8-3.0.jar

**Comment by lumien231** [comment]
Yes :P, the 1.8 version contains completely different stuff and currently does not have a config file or commands.

Also for 1.8 i moved the Bloodmoon to it's own mod (http://minecraft.curseforge.com/mc-mods/226321-bloodmoon)
