### ISSUE TITLE
Block Breaker not breaking blocks

### ISSUE THREAD

**Issue by WtfShipoopi** [lumien231/Random-Things#110]
3.7.5
forge 2050

After placing the block breaker it acts like its breaking the block gets about 95% done and then nothing... 
Placing or breaking a block on any side on the block breaking makes it start hitting the block again without completing..

**Comment by lumien231** [comment]
Works fine for me, can you reproduce this with only Random Things installed?

**Comment by WtfShipoopi** [comment]
Found the issue to be protected area... Does anyone know the uuid that is used so it can be added to a whitelist?

**Comment by lumien231** [comment]
Name: RTBlockBreaker

UUID: 1ea68f0e-8ba7-32ae-9283-0069f8586bfb
