### ISSUE TITLE
[Suggestion] keep 1.7.10 updated as well

### ISSUE THREAD

**Issue by Ianaver** [lumien231/Random-Things#112]
can you please update 1.7.10 too? 1.8 (the first release of 1.8.X series) is still really buggy, laggy and that is the version that forge is on, so that the extreme dupe glitches and game breaking bugs in the game it self still exist in that release.

**Comment by lumien231** [comment]
Forge is on 1.8 now. So i'm developing for 1.8. Also i didn't notice "Really buggy and laggy" stuff.

**Comment by Ianaver** [comment]
https://mojang.com/page/2/ (info for fixes right after 1.8, scroll untill you see fixes for 1.8.2) https://mojang.com/ (wither skull dupe among other big bugs)
