### ISSUE TITLE
[Feature request] Ability to disable blocks / content in the config file

### ISSUE THREAD

**Issue by Lothrazar** [lumien231/Random-Things#113]
Lots of amazing stuff in here, but It would be awesome for modpack makers to be able to disable certain items or blocks.  

For example, a config category that lists every block and item, and we could set to false, restart the world and have that thing removed.  For balance and such.  I know this is no small task, but yeah. :)

**Comment by lumien231** [comment]
"I know this is no small task, but yeah :)"

Exactly, and there are already mods out there that allow you to change recipes so i don't have to add all the config options myself :).

I only add config options for stuff you can't _disable_ through recipe changing. (Like Worldgen)
