### ISSUE TITLE
Fertrilized dirt rejecting some crops

### ISSUE THREAD

**Issue by ghost** [lumien231/Random-Things#114]
When planting certain crops the fertilized dirt accepts them and then ejects them a second later. Vanilla crops work fine, but strawberries and peanuts (Pam's HarvestCraft) and fluffy puff seed (Silent's Gems) can't be grown there.

**Comment by lumien231** [comment]
SilentChaos512/SilentGems#59

**Comment by lumien231** [comment]
MatrexsVigil/harvestcraft#154

**Comment by rigerc** [comment]
Can confirm this. A single crop plants ok, but if you place 2 custom crops side by side they get ejected. Planting in checkerboard pattern works.

https://github.com/MatrexsVigil/harvestcraft/issues/166

**Comment by lumien231** [comment]
Well yeah, it's already confirmed. But the mods the plants are from have to fix this. (At least in the case of Harvest Craft)

**Comment by xChitose** [comment]
Happens with Agricultural Expansion, and Mystical Agriculture, so far that I've tested. 

Also, I've found that using a planter from Progressive Automation will plant the crops, but on the regular Fertilized Dirt, not Tilled Fertilized Dirt (though I will test this) and they seem to grow and get replanted. 

Once I'm home (or if someone does now) I will test to see if the EIO Farming Station will plant.

Edit:

EIO Farming Station did not plant on the Fertilized Dirt regular or tilled. 

Progressive Automation Planter only plants on non-tilled Fertilized Dirt.

**Comment by lumien231** [comment]
xLionel775/AgriculturalExpansion#22

**Comment by lumien231** [comment]
https://minecraft.curseforge.com/projects/mystical-agriculture/issues/23

**Comment by lumien231** [comment]
@xChitose EIO Farming Station works fine for me (With Vanilla Crops), does it not work for you?

**Comment by xChitose** [comment]
@lumien231 Yes, it works fine for vanilla crops. 

I was referring solely to modded crops on your soil. 

Also, thanks for replying and informing the mod developers!

**Comment by lumien231** [comment]
@xChitose The crops that aren't working on fertilized dirt planted manually won't work in the farming station either. The Fluffy Puff seeds from Silent Gems which fixed that work fine.

**Comment by xChitose** [comment]
@lumien231 Yeah, my work around will be the Progressive Automation Planter until the mod authors update their crops.
