### ISSUE TITLE
[Major Problem]Trying to play/create a world but put into main menu instead

### ISSUE THREAD

**Issue by JAWSAWN** [lumien231/Random-Things#114]
I'm using the 1.7.10 - 2.2.4 With other mods, Forge Version 10.13.2.1352 With more mods custom modpack.

I don't get any crash reports from mc itself nor the open eye.
But I left the Game output on, so this is the output everytime I try to open a saved world:

http://paste.ubuntu.com/10762084/

**Comment by JAWSAWN** [comment]
Dimension conflict perhaps?

**Comment by lumien231** [comment]
Yes, change the id of the spectre dimension in the config file.

**Comment by JAWSAWN** [comment]
Ah, thanks for that. Quick reply btw! I'll look into that, I guess I'm going to murder your config file ;)

By the way, are 1.7.10 builds now unsupported or still supported? Keep the good work!

**Comment by lumien231** [comment]
They are unsupported in that there won't be anymore updates.
