### ISSUE TITLE
By lumien's request: "screnshot of the redstone thing"

### ISSUE THREAD

**Issue by CoolioWolfus** [lumien231/Random-Things#117]
![2016-08-23_22 35 05](https://cloud.githubusercontent.com/assets/21157043/17910886/c18460a8-6982-11e6-9d90-8839c7f82ad9.png)
![2016-08-23_22 36 34](https://cloud.githubusercontent.com/assets/21157043/17910885/c181a5c0-6982-11e6-9d0a-5b1c83e1e8c5.png)

**Comment by lumien231** [comment]
This is just a minecraft thing, blocks that can provide power themselves don't "transmit" power like that. I don't think this causes much inconvenience either so i won't try to change it.

**Comment by lumien231** [comment]
Didn't read your post on curseforge, does this cause any issues for you? If so could you post a build where it does?
