### ISSUE TITLE
Server console NPE being caught.  Reporting it for your use

### ISSUE THREAD

**Issue by utoc** [lumien231/Random-Things#118]
Hello

Paste here: http://pastebin.com/iXHtgHhs
Full log here: https://gist.github.com/utoc/dfb10e45537731570f59eb4ad11e7918

We're running FML 2073 and RandomThings 1.10.2-3.7.5

This NPE comes up when a user tries opening the Redstone Remote.  Other than the NPE; I don't see any negative side effects.  Just passing it along for your use.

**Comment by lumien231** [comment]
So the Redstone Remote still works fine after the NPE?

**Comment by utoc** [comment]
As best we can tell, everything works as intended.
