### ISSUE TITLE
Crashing after install

### ISSUE THREAD

**Issue by ghost** [lumien231/Random-Things#12]
After installing the mod with, CodeChickenCore, Ex Nihlo 2, Gravity Gun, Hopper Ducts, iChunUtil, Mouse Tweaks and Not enough items, I crash with the following.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.8-3.5.3.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2015/07/17 12:24 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at lumien.randomthings.worldgen.WorldGenCores.placeNatureCore(WorldGenCores.java:243)
    at lumien.randomthings.worldgen.WorldGenCores.generate(WorldGenCores.java:201)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:270)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1126)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:180)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:122)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:112)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:126)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 199919632 bytes (190 MB) / 364429312 bytes (347 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx3072m
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1491 11 mods loaded, 11 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAA mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAA FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.3.1491.jar) 
    UCHIJAA Forge{11.14.3.1491} [Minecraft Forge](forge-1.8-11.14.3.1491.jar) 
    UCHIJAA CodeChickenCore{1.0.5.36} [CodeChicken Core](minecraft.jar) 
    UCHIJAA NotEnoughItems{1.0.5.104} [Not Enough Items](NotEnoughItems-1.8-1.0.5.104-universal.jar) 
    UCHIJAA exnihilo2{0.27} [Ex Nihilo 2](ExNihilo2-0.27.jar) 
    UCHIJAA iChunUtil{5.4.0} [iChunUtil](iChunUtil-5.4.0.jar) 
    UCHIJAA GravityGun{5.0.0} [GravityGun](GravityGun-5.0.0.jar) 
    UCHIJAA hopperducts{1.4.5} [Hopper Ducts](hopperducts-mc1.8-1.4.5.jar) 
    UCHIJAA MouseTweaks{2.5.0} [Mouse Tweaks](MouseTweaks-2.5.0-mc1.8.jar) 
    UCHIJAA RandomThings{3.5.3} [Random Things](RandomThings-MC1.8-3.5.3.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.8-3.5.3.jar)
  lumien.randomthings.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)

NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  net.fybertech.nwr.NowWithRendering
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by lumien231** [comment]
Do you also crash with only Random Things installed?
