### ISSUE TITLE
Mod is Incompatible with latest Forge Version

### ISSUE THREAD

**Issue by zzApotheosis** [lumien231/Random-Things#120]
Minecraft 1.7.10
MCP v9.05
FML v7.10.137.1399
Minecraft Forge 10.13.3.1399

It worked perfectly fine in Minecraft Forge 10.13.3.1395, but in the latest version, I can't even start the game without crashing. I tested thoroughly, even attempting to launch the game with just this mod, and it still crashed. I know you're focusing on 1.8, but 1.7.10 is still currently the focus of Minecraft modding, so please release a fix for the latest 1.7.10 Forge.

Here's my crash log: http://pastebin.com/NdHvExxP

**Comment by lumien231** [comment]
Forge "accidentally" broke all core mods with the latest update, they reverted that change so this should be fixed in the next forge version
