### ISSUE TITLE
EnderIO + Random Things redstone can crash servers.

### ISSUE THREAD

**Issue by Claycorp** [lumien231/Random-Things#122]
http://pastebin.com/yTzf3Xxc

I have no idea what the exact item is that's causing the issue but it looks like any redstone could cause it from the crash.

**Comment by lumien231** [comment]
Can you reproduce this in a fresh world?

**Comment by Claycorp** [comment]
I could not reproduce it in singleplayer. I don't know the exact specifics that's triggering it.
The person is using an advanced redstone interface with filters and then switches them out as needed but the crash is happening when people are switching dimensions on the server.

**Comment by lumien231** [comment]
kk, will try to just make it a bit more "secure" then

**Comment by Claycorp** [comment]
Thanks! It does seem to be quite random as it works fine then randomly on someone switching DIM's it will crash.
