### ISSUE TITLE
Minecraft doesn't start up with Random-Things installed

### ISSUE THREAD

**Issue by HDLawrence** [lumien231/Random-Things#122]
I am running FTB Infinity and decided I wanted to add Random Things mod because it wasn't included in the original mod pack. When I added the mod Minecraft wouldn't ever finish booting. I have tried all version of Random Things. 
Here is a link to my log file: 
http://pastebin.com/zpN4SCyd

**Comment by dankfrog** [comment]
remove the fast leaf decay mod.

**Comment by lumien231** [comment]
^

Random Things itself has Fast Leave Decay (In 1.7.10)

**Comment by HDLawrence** [comment]
Thanks!
