### ISSUE TITLE
Game dosent Start

### ISSUE THREAD

**Issue by maginator** [lumien231/Random-Things#127]
Hi. Minecraft dosent Start with Random Thinks. Pleas Help.

Crashreport 

[B#347]  [18:09:19] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#347]  [18:09:19] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#347]  [18:09:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[B#347]  [18:09:19] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[B#347]  [18:09:19] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_101, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_101
[B#347]  [18:09:19] [main/INFO] [FML]: [AppEng] Core Init
[B#347]  [18:09:19] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:19] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:19] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:19] [main/INFO] [FML]: Loading tweaker fastcraft.Tweaker from fastcraft-1.23.jar
[B#347]  [18:09:19] [main/INFO] [FML]: Loading tweaker forestry.shade.javacheck.Java7Checker from forestry_1.7.10-4.2.14.62.jar
[B#347]  [18:09:19] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:19] [main/WARN] [FML]: The coremod mrtjp.relocation.asm.RelocationPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.DepLoader$DepLoadInst:<init>:333]: MicdoodleCore searching for dependencies in mods file: P:\Minecraft\technic\modpacks\editftbcrackpack\mods
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod mrtjp.core.handler.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod pcl.opensecurity.util.SoundUnpack does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#347]  [18:09:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[B#347]  [18:09:20] [main/INFO] [LaunchWrapper]: Loading tweak class name fastcraft.Tweaker
[B#347]  [18:09:20] [main/INFO] [LaunchWrapper]: Loading tweak class name forestry.shade.javacheck.Java7Checker
[B#347]  [18:09:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[B#347]  [18:09:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[B#347]  [18:09:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[B#347]  [18:09:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[B#347]  [18:09:21] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [Aroma1997Core]: Finished data injection.
[B#347]  [18:09:21] [main/INFO] [Aroma1997Core]: Finished data injection.
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [IC2-core]: Loaded library EJML-core-0.26.jar.
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [INpurePreloader]: Attempting to detect JVM version...
[B#347]  [18:09:21] [main/INFO] [INpurePreloader]: Detected JVM: 1.8
[B#347]  [18:09:21] [main/INFO] [INpurePreloader]: Starting library configuration...
[B#347]  [18:09:21] [main/INFO] [INpureLogInterceptor]: System attached to FML. Now intercepting all logging calls.
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
[B#347]  [18:09:21] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[B#347]  [18:09:21] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class forestry.shade.javacheck.Java7Checker
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class fastcraft.Tweaker
[B#347]  [18:09:22] [main/INFO] [FastCraft]: FastCraft loaded.
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[B#347]  [18:09:22] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[B#347]  [18:09:22] [main/INFO] [RandomThingsCore]: Found World Class: net/minecraft/world/World
[B#347]  [18:09:22] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[B#347]  [18:09:22] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: sa (1 / 1)
[B#347]  [18:09:22] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: bdi (1 / 1)
[B#347]  [18:09:22] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Transformed
[B#347]  [18:09:22] [main/INFO] [AE2-CORE]: func_146977_a_original(Lnet/minecraft/inventory/Slot;)V - New Method
[B#347]  [18:09:22] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Invoke Virtual
[B#347]  [18:09:23] [main/INFO]: Setting user: Magi_nator
[B#347]  [18:09:23] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: xk (1 / 1)
[B#347]  [18:09:23] [main/INFO] [RandomThingsCore]: Found Item Class: net/minecraft/item/Item
[B#347]  [18:09:23] [main/INFO] [FastLeafDecay]: Patching leaves.
[B#347]  [18:09:23] [main/INFO] [FastLeafDecay]: Found leaf Class: net/minecraft/block/BlockLeavesBase
[B#347]  [18:09:23] [main/INFO] [RandomThingsCore]: Found Leave Class: net/minecraft/block/BlockLeavesBase
[B#347]  [18:09:23] [main/ERROR] [LaunchWrapper]: Unable to launch
[B#347]  java.lang.reflect.InvocationTargetException
[B#347]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
[B#347]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#347]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
[B#347]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#347]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#347]  Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockOldLeaf
[B#347]     at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
[B#347]     at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
[B#347]     at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
[B#347]     at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
[B#347]     ... 6 more
[B#347]  Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockOldLeaf
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
[B#347]     at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
[B#347]     at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
[B#347]     at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
[B#347]     ... 6 more
[B#347]  Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.block.BlockLeaves
[B#347]     at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-17.0.jar:?]
[B#347]     at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94) ~[CoFHCore-%5B1.7.10%5D3.1.2-325.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
[B#347]     at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
[B#347]     at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
[B#347]     at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
[B#347]     ... 6 more
[B#347]  Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockLeaves
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
[B#347]     at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90) ~[CoFHCore-%5B1.7.10%5D3.1.2-325.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
[B#347]     at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
[B#347]     at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
[B#347]     at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
[B#347]     ... 6 more
[B#347]  Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.block.BlockLeavesBase
[B#347]     at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-17.0.jar:?]
[B#347]     at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94) ~[CoFHCore-%5B1.7.10%5D3.1.2-325.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
[B#347]     at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90) ~[CoFHCore-%5B1.7.10%5D3.1.2-325.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
[B#347]     at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
[B#347]     at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
[B#347]     at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
[B#347]     ... 6 more
[B#347]  Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockLeavesBase
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
[B#347]     at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90) ~[CoFHCore-%5B1.7.10%5D3.1.2-325.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
[B#347]     at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90) ~[CoFHCore-%5B1.7.10%5D3.1.2-325.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
[B#347]     at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
[B#347]     at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
[B#347]     at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
[B#347]     ... 6 more
[B#347]  Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file net/minecraft/block/BlockLeavesBase
[B#347]     at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
[B#347]     at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90) ~[CoFHCore-%5B1.7.10%5D3.1.2-325.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
[B#347]     at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
[B#347]     at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90) ~[CoFHCore-%5B1.7.10%5D3.1.2-325.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
[B#347]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
[B#347]     at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
[B#347]     at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
[B#347]     at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
[B#347]     at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
[B#347]     ... 6 more
[B#347]  Exception in thread "main" [18:09:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[B#347]  [18:09:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[B#347]  [18:09:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.SecurityManager.checkExit(Unknown Source)
[B#347]  [18:09:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.Runtime.exit(Unknown Source)
[B#347]  [18:09:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.System.exit(Unknown Source)
[B#347]  [18:09:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[B#347]  [18:09:23] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Mods Installed
MC 1.7.10
Minecraft Forge 10.13.4.1614
Ae2 Stuff
Agricraft
Anotherbitethedust
applied energistics
Aroma1997Core
Aroma1997 Mining World
Bdlib
Biblocraft
Biblowoods Forestry
Biblowoods Natura
Big Reactors
Binnie Patcher
Binnie mods
Botania
Brandons Core
Buildcraft
CarpentersBlocks
Catwalks
 Mrcrayfish furniture
Chicken Chunks
Chisel
Code Chicken Core
CofhCore
Cofhlib
Compact Machines
Computercraft
Cookingbook
CraftTweaker
CustomMainMenu
Decocraft
Denseore
Draconic Evolution
EnderCore
Ender IO
Ender Storage
Ender Tech
Enhanced Portals
Extra Cells
Extra TCI
Extra Utillities
Factorization
Fastcraft
FastLeaveDecay
FlatSigns
Forestry
ForgeAnalytics
FTBLib
FTBUtilities
Funy Locomotion
Galacticraft Core
Galacticraft Planets
Guid Api
IC2 Nuclear Controll
iChunUtil
IguanaTinkerTweaks
ImmersiveEngineering
Industrial Craft
INpureCore
IntelligentEnergistics
InventoryTweaks
Ironchest
Jabba
Journeymap
LogisticsPipe
Mantle
MatterOverdrive
mcjtylib
Mekanism v9 (Generators, Tools)
MicdoodleCore
Minefactory Reloaded
Modular Powersuit
Morpheus
Natura
NEI Addons
NEI Integration
Nether Ores
No MoreRecipeConflic
NEI
Numina
OpenBlocks
OpenComputers
OpenModsLib
OpenModularTurrets
OpenPeripheralAddons
OpenPeripheralCore
OpenPeripheral Integration
OpenRadio
OpenSecurity
Pams Harvestcraft
Player API
Pneumaticcraft
Portalgun
Project Red(Base,Compact, Fabrication, Interation, Lighting, Mechanical, World)
Railcraft
RecallStones
RedstoneArsenal
RFTools
Roguelike Dungeons
Realisic Terrain Generation
SimplyJetpacks
SolarFlux
StorageDrawers (Foresty, Misc, Natura)
TinkersConstruct
Thermal Dynamics
Thermal Expansion
Thermal Foundation
TinkersConstruct Tooltips
Tinkers Mechworks
Veinminer
Vending
Waila (Harvestability, Plugins)
Wawla
WirelesCraftingTerminal
Witchery
WR-CBE

LG Magi

**Comment by lumien231** [comment]
Remove FastLeaveDecay, it's included in Random Things.
