### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by jadenPete** [lumien231/Random-Things#13]
Sometimes my game crashes, and it mentions your mod in the crash report. Here's my crash report:
http://pastebin.com/hmFkyMru

**Comment by lumien231** [comment]
I assume you are using a Redstone Interface, could you post a screenshot of the setup / What it's connected to?

**Comment by jadenPete** [comment]
Well, I use many redstone interfaces in my world, but here's the closest ones when it crashes:
![2015-07-18_12 45 58](https://cloud.githubusercontent.com/assets/13180372/8763334/a0e9609c-2d4b-11e5-8a9f-98f1cd72b726.png)
![2015-07-18_12 46 12](https://cloud.githubusercontent.com/assets/13180372/8763335/a6f2f958-2d4b-11e5-8d67-7ecf6f32d72d.png)

**Comment by lumien231** [comment]
Why are there 2 of them on top of each other? o_O

**Comment by jadenPete** [comment]
Both are being powered. It's for a piston door. In these screenshots, i'm underground.

**Comment by lumien231** [comment]
Hmm, will try to fix this next version.

Just in case you don't know though, you don't need a redstone interface on the receiving side. You can bind them to any block.

**Comment by jadenPete** [comment]
I know. It's very convenient :)

**Comment by jadenPete** [comment]
Btw, i'm using 1.8

**Comment by lumien231** [comment]
Redstone Interfaces only exist in 1.8^^.  So are both of these images the "sending" side then?

**Comment by jadenPete** [comment]
Yes, each image shows 2 ri's linked to one side (two pistons). So when I pull a lever, all four ri's are powered, therefor powering all four pistons, and closing the piston door.

**Comment by jadenPete** [comment]
Can you fix this?

**Comment by lumien231** [comment]
I will once i have access to my pc again :) (On Sunday)

**Comment by jadenPete** [comment]
Ok, thanks. This has really been "bugging" me. Get it? Sorry for my cheesy jokes.
