### ISSUE TITLE
crash on startup ;-;

### ISSUE THREAD

**Issue by ghost** [lumien231/Random-Things#135]
[crash-2016-09-27_18.43.13-client.txt](https://github.com/lumien231/Random-Things/files/495369/crash-2016-09-27_18.43.13-client.txt)

**Comment by lumien231** [comment]
Does this happen everytime you start the game?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
sorry its not your mod its this one : https://minecraft.curseforge.com/projects/ex-nihilo-omnia/files/2332458
