### ISSUE TITLE
[1.7.10] Item Coloring command bug

### ISSUE THREAD

**Issue by Shahelion** [lumien231/Random-Things#139]
When using the command on an item that also shows the hand holding it, the hand is colored but the item is not. Ignore the error in the chat, that was from trying an invalid color code.
![2016-09-30_21 30 28](https://cloud.githubusercontent.com/assets/6917535/19011770/6f67ad2a-8755-11e6-82e9-fce4a0e6523a.png)
![2016-09-30_21 30 36](https://cloud.githubusercontent.com/assets/6917535/19011769/6f65e896-8755-11e6-8279-8ff17dab8b2d.png)

**Comment by lumien231** [comment]
I can't tint custom renders like that. So i can't fix this.

**Comment by Shahelion** [comment]
I thought that might be the case. What's the command or color code to revert to default, if there is one?

**Comment by lumien231** [comment]
Setting the tint to white should turn it back to normal.
