### ISSUE TITLE
Crash w/ Extra Utils 2

### ISSUE THREAD

**Issue by WenXin20** [lumien231/Random-Things#142]
Forge 1.10.2-2092
Random Things 3.7.6
[Extra Utils 1.1.0a](https://minecraft.curseforge.com/projects/extra-utilities)
Crash on load w/ the newest Extra Utils version
[Crash Log](http://pastebin.com/vmg81MtJ)

**Comment by lumien231** [comment]
How do you know it's Extra Utilities & Random Things? Can you reproduce this with only those 2 mod installed?

**Comment by UnNinja** [comment]
I was actually just about to open a report for this. Random Things works fine with earlier versions of ExtraUtilities, but things go splat when I try and update extra utilities

**Comment by WenXin20** [comment]
Yeah, that's what happened to me, after I downgraded extra Utils back to 1.0.1, random things worked fine.

**Comment by WenXin20** [comment]
I just tried just these two mods by themselves and it worked fine, it looks like the could be a third mod involved.

**Comment by UnNinja** [comment]
Looks like this is ExU and Optifine, more than exu and randomthings

**Comment by lumien231** [comment]
I think it might be load order dependent so whether it crashes with a certain set of mods is kinda random. It would be interesting if you could reproduce it only with or without optifine installed.

**Comment by lumien231** [comment]
Ok so it does actually appear to happen with Optifine & Extra Utilities installed.

**Comment by sp614x** [comment]
Found the problem, it only happens with mods which use delayed sprite registration.
Updated preview OptiFine C4 with a bugfix.

**Comment by lumien231** [comment]
Neat :), just tried it and it seems to work fine now. Closing this.

**Comment by xChitose** [comment]
How did you come upon the solution, @sp614x ?

**Comment by sp614x** [comment]
One Forge hook was missing from TextureMap. 
It can be used by mods to organize delayed atlas sprite registration, which is rarely used.
