### ISSUE TITLE
[1.10.2] Crash/issue with OptiFine

### ISSUE THREAD

**Issue by jod4** [lumien231/Random-Things#143]
I'm not sure if you support / want to support OptiFine but I just stumbled across this crash. Only happens when OptiFine is in the modlist, so...

Forge version is 1.10.2-**2099**
Random Things **3.7.6**
The crash happens when minecraft does its initialisation rite.
[**Here's the report**](http://pastebin.com/YGgR5ZAn)

**Comment by lumien231** [comment]
This is #142, it's an issue between optifine and extra utilities.
