### ISSUE TITLE
Breaker glitch - infinite OpenBlocks full tank

### ISSUE THREAD

**Issue by fipil** [lumien231/Random-Things#146]
Hi,
I'm using the version 1.9 of the Random Thing in my MC1.6.4 server. There is also installed the OpenBlocks 1.2.8 mod. There is a fluid tanks in the OpenBlocks, which can contain any fluid, for example Water, Lava or IC2 UU-Matter. 
How to reproduce glitch:
1. Put Breaker to ground and next to it a chest, so the breaker fills the chest by blocks.
2. Put ONE OpenBlocks tank full of any fluid, for example lava, into the chest.
3. Place an EMPTY OpenBlocks tank next to the Breaker, so breaker breaks the tank, get it and put it to the chest.
4.  Look into the chest - there is two full tanks of the liquid (lava), instead of one empty and one full of lava.

I don't know if it's bug in the OpenBlocks or in the Random-Things.
Can you help me please?
Thanks
Fipil.

**Comment by lumien231** [comment]
Sorry but i don't support the 1.6.4 version anymore :/.
