### ISSUE TITLE
1.10.2 Crash with Optifine 

### ISSUE THREAD

**Issue by TheDeadGamer** [lumien231/Random-Things#147]
Launched Minecraft with 

-Xmx4051m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Games\Minecraft\Instances\1_10_2 Modpack" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M 
those arguments using Forge 12.18.2.2105

 Minecraft fails to launch during the end of third or start of 4/7 Minecraft loading sequence; and using the latest version of Random Things and Optifine. Disabling Optifine fixes the crash. Just wanted to make you aware.

Crash report is uploading in a .txt document so as not to make it annoying to read.

[New Text Document.txt](https://github.com/lumien231/Random-Things/files/527291/New.Text.Document.txt)

**Comment by lumien231** [comment]
Thanks for making me aware :)

#145
