### ISSUE TITLE
[1.10.2] [3.7.6] Ticking Block Entity (RedstoneSignalHandler)

### ISSUE THREAD

**Issue by Alaberti** [lumien231/Random-Things#148]
Player had this issue in a single player world, says all he did was type /help 2. @Vazkii, your open crate seems to be involved too, I'll open a ticket there if you like.

http://pastebin.com/4zxcx9GW
http://prnt.sc/cv6h7e

**Comment by Alaberti** [comment]
The plot thickens. Exception in server tick loop: http://pastebin.com/bEFvx7MQ

**Comment by MushroomDynamo** [comment]
I am encountering this issue as well; running /help yields a very similar crashlog (no open crate though).
