### ISSUE TITLE
[1.10.2] [3.7.6] Specter Dimension has some pest issues.

### ISSUE THREAD

**Issue by 63502** [lumien231/Random-Things#149]
I seem to have a constant infestation of Pigmen and the occasional Ghast on the roof of my specter dimension. 
![2016-10-18_12 44 30](https://cloud.githubusercontent.com/assets/15267053/19487503/251f53e6-9531-11e6-881a-2d765edc6c93.png)
While I appreciate the free safe xp and drops when using the Extra Utils Magic Boomerang, I am not entirely sure that this behavior is intentional, and the noise is getting to be stupidly annoying. 

Is the Spectre Dimension being a Hell biome and being spawnable outside of the main box a bug?

*Edit: It should be noted that other than the above, all other Specter Key/Dim features seem to be working just fine for me.

**Comment by 63502** [comment]
The infestation seems to have spread into the walls...
![2016-10-18_15 15 52](https://cloud.githubusercontent.com/assets/15267053/19493009/e78fbb72-9546-11e6-87f3-63f82fec25f4.png)

**Comment by lumien231** [comment]
Can you reproduce this without other mods installed?

**Comment by 63502** [comment]
Without any extra mods, the Specter Dimension seems to not only be nether mob free, it's also an entirely different color.
![2016-10-28_10 26 34](https://cloud.githubusercontent.com/assets/15267053/19809997/aeff40d8-9cf9-11e6-8672-1297a1d717c4.png)
![2016-10-28_10 26 37](https://cloud.githubusercontent.com/assets/15267053/19810000/b08733f2-9cf9-11e6-9d1f-c467e3326b2f.png)
So, no. I can't reproduce the pigman infestation without extra mods. The biome is still hell, although water can be placed.

**Comment by lumien231** [comment]
This _should_ fix this, if you still notice it next version reopen this.
