### ISSUE TITLE
Cannot disable beans/magic beans

### ISSUE THREAD

**Issue by Siigari** [lumien231/Random-Things#150]
RandomThings-MC1.10.2-3.7.6

Set:

worldgen {
    B:Beans=false
    B:Nature-Core=true
    B:PitcherPlants=true
    B:Sakanade=true
    B:WaterChest=true
}

and beans still show up in chests.

**Comment by lumien231** [comment]
I assume you are talking about the nature core chest?

**Comment by Siigari** [comment]
Yes.
