### ISSUE TITLE
Placing Fertilized dirt "eats" dropped items? - more of a question

### ISSUE THREAD

**Issue by MoonCutter2B** [lumien231/Random-Things#151]
While replacing my normal farmland with fertilized dirt I noticed that it looks like blocks "floating around" wasn't pushed away when placing the new block. In this case it looked like the normal dirt was "eaten" and destroyed by the new block. I will test again later today to see if I can repeat it.

**Comment by lumien231** [comment]
Seems to work fine for me, you'll have to show me how to reproduce this

**Comment by MoonCutter2B** [comment]
first I created a 1x1x1 pit of stone and dropped some dirt and some other stuff into it and then placed a fertilized dirt in the pit, all items poped up but a bit wobbly and slow. I.e works.
then I went back to my farming area and did the same but with dirt on all sides of the pit. The dropped items did not pop up. I then used my shovel on the fertilized dirt and there was my missing items. I repeated this a few times and the dropped items was there every time.
Maybe its some other mod involved.
I could do some more testing if you need.

**Comment by lumien231** [comment]
I can't reproduce this, the items just fly out of it. Were you able to reproduce this more then once?

**Comment by MoonCutter2B** [comment]
Hi!, 
No, today it works as expected. A lot of other mods has been updated including Forge since I tested it last. So it looks like the problem is gone. 
So I think we can close this "issue"

**Comment by lumien231** [comment]
Ok nice :)
