### ISSUE TITLE
Spectre Dimension might not be working properly on linux

### ISSUE THREAD

**Issue by Sunconure11** [lumien231/Random-Things#152]
One of my friends is trying to host a hermitcraft server, and he encountered this issue with Random Things. Removing the mod solved the issue, but the machine it was being hosted on is linux (multicraft server), but he was able to run it fine on a windows machine with Random Things. As a result, I believe Random Things might be incompatible to some extent with linux-based machines.

This is the crash report:

http://pastebin.com/tiv3kFyR

**Comment by lumien231** [comment]
Weird, can you also reproduce this with no other mods installed?

**Comment by Sunconure11** [comment]
As it happened on a Linux machine that I only have remote access to, reproducing it would likely not have the same results.

However, as mentioned before, the issue did not happen for the user when he ran it on a windows machine.

**Comment by lumien231** [comment]
So you don't have another linux machine you can test it on?

**Comment by Sunconure11** [comment]
Correct. I will see about looking into something else to fix it. I will re-open this if I find nothing to help.

**Comment by Sunconure11** [comment]
I tried what you said, about seeing if the forge jar is corrupt, but nothing seems to have solved the issue. I could set up a virtual linux machine to see about testing this, but I feel like I would get poor performance that might interfere with determining if this is an OS issue, despite having a beefy machine.

Could you add an option to change the dimension ID via the config at least? I feel like that might solve this issue. Since if I am interpreting it right, the mod is trying to find a random ID to assign the dimension to, but it is somehow selecting an invalid ID.

Either way, thanks for your time.
