### ISSUE TITLE
Block Breaker doesn't function in FTB Utilities protected chunk

### ISSUE THREAD

**Issue by kaitoyuuki** [lumien231/Random-Things#154]
I have no idea if this is intentional, or if you're using a fakeplayer to use the block breaker, but I'd really appreciate a way around this. We can't add fakeplayers as ops anymore due to the new OP system (have to have UUIDs), and I don't think I can add a fake player to my FTBu team.

**Comment by lumien231** [comment]
The Block Breaker uses a Fake Player which does have a UUID, it should be printed in the debug log starting with "BlockBreakerUUID"

**Comment by kaitoyuuki** [comment]
I can't seem to find this debug log, or where it would go, nor how to actually make this verbose. Is there no list of possible block breaker UUIDs? or do they get randomly assigned or something?

alternatively, having a method to print RandomThings' various UUIDs being used on the server to a file would be really helpful. (I really wish forge had a method to do this for all mods built in.)

**Comment by lumien231** [comment]
It's "1ea68f0e-8ba7-32ae-9283-0069f8586bfb", the debug log is logged to fml-client/server-latest.log

**Comment by kaitoyuuki** [comment]
Oh, thanks. This is super helpful. I still can't seem to find that line in any of the log files, but having the UUID should hopefully fix any issues.
