### ISSUE TITLE
Accidentally Broke the Mod, Don't know how to fix

### ISSUE THREAD

**Issue by ghost** [lumien231/Random-Things#155]
So, I had a redstone interface remotely turning a SSTOW spawner on and off and randomly, when I logged into my server, the game was crashing because of the interface. To fix this, I figured I'd just remove Random Things, load the world, then add the mod back in. However, now that I've done that, whenever I attempt to craft any of the items from the mod, the game crashes. When I look at the items from the mod in JEI, it says "Tooltip error, see log"

Here is the crashlog: http://pastebin.com/1DPtVVgD
Here is the game log: http://pastebin.com/xX3APYXV

**Comment by lumien231** [comment]
Do you not have a crash log for the interface crash?

**Comment by ghost** [comment]
Didn't I give the crash log?

**Comment by lumien231** [comment]
Both of the logs look like they are from the "crafting" crash, not the interface one.

**Comment by ghost** [comment]
Like as in the broken tool tips in JEI? It doesn't crash the game, just
they don't show up correctly. When I get home I'll try to get some
screenshot so you can see what I mean

**Comment by lumien231** [comment]
"now that I've done that, whenever I attempt to craft any of the items from the mod, the game crashes" The crash logs are for this right? 
Do you also have some for 
"I had a redstone interface remotely turning a SSTOW spawner on and off and randomly, when I logged into my server, the game was crashing because of the interface" this?

**Comment by ghost** [comment]
I fear it may be corruption within my world file or something. When I
removed random things originally, I had to confirm the missing blocks and
items on the server (with /fml confirm) but when I added it back in, it
didn't ask me to confirm changes for the new blocks like it usually would.

**Comment by ghost** [comment]
Ah yes, I do. That could either be a bug in the interface or the way the
spawned handles Redstone input. I'm sure if I put a piece of Redstone next
to it and powered that instead, it would work fine. I'll upload the log
when I get home.

**Comment by ghost** [comment]
Here's the crash report: http://www.pastebin.com/wVEyt7eN

**Comment by ghost** [comment]
Welp, better go off myself. Somehow, the mod wasn't even running on the server, so that's why it was giving errors :/ I'm stupid. Anyways, there is still the issue of the game crashing when you use a redstone interface with the spawners, but it doesn't even do it as soon as you activate it so I have no idea what's causing that.
