### ISSUE TITLE
NPE on initializing game

### ISSUE THREAD

**Issue by Syndaryl** [lumien231/Random-Things#157]
Crash report attached to ticket. Since this started after I updated a bunch of mods at the same time, I assume it's a conflict. The problem is I did a bunch at once so I'm not 100% sure which... but one of the following:

"DrZharks CustomMobSpawner 3.10.1.jar"
"DrZharks MoCreatures Mod-10.0.6.jar"
"Pam's HarvestCraft 1.9.4-1.10.2h.jar"
[1.10.2]UtilityBlocks-5.0.4-universal.jar
AnalogueRS-1.1.jar
BiomesOPlenty-1.10.2-5.0.0.2091-universal.jar
CookingForBlockheads_1.10.2-4.2.26.jar
covers-0.4.1.13-mc1.10.2.jar
exnihiloomnia-1.1.5.jar
extrautils2-1.10.2-alpha-1.2.1.jar
LunatriusCore-1.10.2-1.1.2.38-universal.jar
Mantle-1.10.2-1.1.1.jar
MCMultiPart-1.3.0-universal.jar
Mekanism-1.10.2-9.2.0.294.jar
MekanismGenerators-1.10.2-9.2.0.294.jar
MekanismTools-1.10.2-9.2.0.294.jar
TConstruct-1.10.2-2.5.6b.jar

[crash-2016-11-04_14.49.04-client.txt](https://github.com/lumien231/Random-Things/files/572404/crash-2016-11-04_14.49.04-client.txt)

**Comment by Syndaryl** [comment]
Follow up: I've pinned it down to my upgrade from _extrautils2-1.10.2-alpha-1.0.1.jar_ to extrautils2-1.10.2-alpha-1.2.1.jar
I tested intermediate versions, and it also gets thrown when I use extrautils2-1.10.2-alpha-1.1.0c.jar

EDIT: Sorry. copy-pasta error had the same version twice which was wrong. Fixed.

**Comment by lumien231** [comment]
This is an issue between Optifine and Extra Utilities, it's fixed in the latest optifine preview version.
