### ISSUE TITLE
Fertilized Dirt turning into regular dirt after the growth of a tree

### ISSUE THREAD

**Issue by nizarnizario** [lumien231/Random-Things#167]
Hi ,
I'm facing a problem with MC saplings ,
after placing a sapling on fertilized dirt, the bonemeal effect work , but after the tree grows , the fertilized dirt turns into regular dirt, so is there any fix for this problem?

Thanks!

**Comment by nizarnizario** [comment]
Anything?

**Comment by lumien231** [comment]
This is a duplicate of #83 , it's a forge / vanilla "bug" so i can't do much about it.
