### ISSUE TITLE
A way to disable Ender Anchors ?

### ISSUE THREAD

**Issue by cauliflower69** [lumien231/Random-Things#173]
I have checked the cfg and can not seem to find a way to disable these blocks. We are troubleshooting some TPS issues and would like to stop them loading chunks.

**Comment by lumien231** [comment]
Will add one next version :).

**Comment by cauliflower69** [comment]
Thanks very much

**Comment by Eufranio** [comment]
Should we delete the config?

**Comment by cauliflower69** [comment]
I have deleted the cfg and I don't see an option to disable it

**Comment by lumien231** [comment]
The config is there from version 3.7.9 for MC 1.11.2 onward.

**Comment by cauliflower69** [comment]
Thanks for the reply.
