### ISSUE TITLE
[1.10.2] Crash on launch

### ISSUE THREAD

**Issue by MrAmericanMike** [lumien231/Random-Things#174]
This is not quiet a bug I believe, as the mod launches ok when I use it on MultiMC, but whenever I try inside Eclipse where I trying to fix some problems with a mod I made, I get this error.

http://pastebin.com/Df1suaMa

Any idea what could be causing this?

Both cases I'm using Forge 12.18.3.2185 and Random Things 3.7.7

**Comment by lumien231** [comment]
"Caused by: java.lang.RuntimeException: Couldn't find MCP mappings."

Random Things requires an mcp folder with mappings inside in the project folder to work in dev environments. You can download mappings [here](http://export.mcpbot.bspk.rs/).

**Comment by MrAmericanMike** [comment]
Thanks a lot ;) I was not good at reading that crash, wasn't sure what was going on.

Once again thanks, I'm trying to fix a "bug" I introduced with some of my mods, one of the where you can "Fart" on crops to make them grow, but when you do it next to the Magic Bean thingy, it regenerates over and over.

https://clips.twitch.tv/vash505/QuaintCheetahPipeHype

Gonna have to check what I'm doing wrong, because it happens also with a watering can I made in another mod, but not with the Extra Utilities one.

**Comment by lumien231** [comment]
I assume you just call Block.updateTick? Maybe you should check whether things are actually plants & whether they receive random ticks before ticking them. Block updates aren't just used for growing stuff after all.

**Comment by MrAmericanMike** [comment]
Yes I had a "bug" on my loop when trying to find growable blocks, but once it found one, all the loop was running true applying world.scheduleBlockUpdate to all the continious loop :S

Thanks for the help and feedback ;)

**Comment by BSFishy** [comment]
I have a question... Why do you need this, even when you are using it as a dependency? xD Just found this, after what seems like years of googling, and sure enough, it fixed my issue... Why oh why, @lumien231 xD

**Comment by lumien231** [comment]
Because it allows me to use srg names for methods / fields in my Class Transformer / Reflection instead of having to always provide both srg and "normal" names.

**Comment by BSFishy** [comment]
But even when it is being used as a dependency? I mean, you could at least put it somewhere that you need to add the mcp folder to your environment. Or say somewhere in the error/log, "HEY! You need to add the mcp folder if you want this mod to work!"

**Comment by lumien231** [comment]
What uses Random Things as a dependency? This only happens when people use it in a dev environment. And if you know how to read a stacktrace it's not exactly hard to find out what's wrong.

**Comment by BSFishy** [comment]
I am saying to use it as a dependency in the dev environment. Just think it is a little annoying how I have to have the mcp folder in **my** environment when I don't really even need to use them myself... 😛

**Comment by maximumsomething** [comment]
Where exactly do these mappings go? Sorry if this is a dumb question, I'm kinda new to modding.

**Comment by lumien231** [comment]
I changed it so it uses the ones from your gradlew instance automatically :).

**Comment by maximumsomething** [comment]
I'm getting this same error though. With Resource Loader, not Random Things.

**Comment by lumien231** [comment]
Well it's only "fixed" in the 1.11.2 version. the mappings have to go in a mcp folder which is in your "main" project folder where your gradlew / build.gradle files are.
