### ISSUE TITLE
Minor Issues with Spectre Dimension

### ISSUE THREAD

**Issue by nrllewellyn** [lumien231/Random-Things#175]
Two minor issues with the spectre dimension:
1.) If you loose your key, you can't exit the dimension.
2.) You can exit the area via any teleportation method from other mods

Suggestions:
1.) Allow the player to exit by right-clicking the spectre core (possibly holding right click or standing still for a while after clicking?)
2.) Have the surrounding area automatically teleport the player back (as if they had used the Spectre Key again) to prevent teleporting out

**Comment by lumien231** [comment]
1 Is a great idea! :D

2 Should already be the case, when you exit the cube you should be teleported back (Unless you are in creative mode)

**Comment by nrllewellyn** [comment]
2. Hrm. Must've had creative mode on. Thanks for the info! :-)
