### ISSUE TITLE
Spectre Dimension Crash

### ISSUE THREAD

**Issue by nrllewellyn** [lumien231/Random-Things#177]
I'm getting a client-side disconnect (NullPointerException in forge) when teleporting to the spectre dimension

From latest.log:
http://pastebin.com/4sc7GsSh

From fml-server-latest.log:
http://pastebin.com/RmySdxMC

If it helps, this only seems to occur when running a dedicated server--local play isn't affected.

Tested with:
Minecraft: 1.10.2
Forge 12.18.3.2185
RandomThings: 1.10.2-3.7.7

**Comment by nrllewellyn** [comment]
Seems to be a cross-mod compatibility issue. Trying to figure out the responsible mod now.

**Comment by nrllewellyn** [comment]
Looks like Random Things is incompatible with Bound Box Outline Reloaded (or vice versa).

Link here, download under the "TL;DR" section:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2345401-bounding-box-outline-reloaded-mod-for-minecraft-1

**Comment by irtimaled** [comment]
Part of the issue if caused by the Spectre dimension is reporting that it is OVERWORLD even though it's not.  Another part is caused by some of my code that wasn't written to handle additional dimensions (which was an oversight by me)

**Comment by irtimaled** [comment]
@lumien231 You should consider registering a new DimensionType rather than reusing Overworld - see this for an example:-
https://git.gildedgames.com/GildedGames/Aether-II/blob/dev/src/main/java/com/gildedgames/aether/common/registry/content/DimensionsAether.java#L26

**Comment by irtimaled** [comment]
I have released an update of the BBOR mod that should stop this happening - check out the forum for details.

**Comment by nrllewellyn** [comment]
@irtimaled Awesome. I'll check it out. Thanks. It'd be nice to see this fixed on Random Things' side too, since I'm sure there's other incompatibilities out there from this :-)
