### ISSUE TITLE
Crash with iron dropper

### ISSUE THREAD

**Issue by Y0ungSandwich** [lumien231/Random-Things#178]
We do use sponge on the server and it is mentioned in the crash report. 

http://pastebin.com/VCPRTkWV

Seems like a bad interaction with a vanilla hopper as reported by a player.

**Comment by lumien231** [comment]
I can't (and don't want to) fix bugs that only happen when sponge is installed. If you can reproduce this on a normal forge server that would be nice :).

**Comment by Y0ungSandwich** [comment]
Well thats just silly. Disregard than.
