### ISSUE TITLE
[1.7.10, 2.2.4] Timing out when logging into server

### ISSUE THREAD

**Issue by ajthemacboy** [lumien231/Random-Things#18]
Hello, I'm having a strange issue that I have linked to RandomThings. I run a custom modpack server, and right after we added RandomThings to the pack, everyone started timing out when logging into the server.. but only for the first time each session.

What I mean is, if we launch the game and login, we'll time out. But then if we login again, we're fine.

Here is the server log for the logins, the first is the time out, the second is then normal login: http://pastebin.com/NQ242MMe

Here is the client log for both as well: http://pastebin.com/1FrSkNfT

Any clue why this is happening? Thanks

**Comment by lumien231** [comment]
Well you do have a dimension id conflict with CompactMachines, maybe try to change their dimension id in the config file?

**Comment by ajthemacboy** [comment]
The CompactMachines dimensionid is 2, is it conflicting, and what should I change it to if it is?

**Comment by lumien231** [comment]
It says in the client log that it does. Maybe change it to 100 or something?

**Comment by ajthemacboy** [comment]
I stopped server, changed config, and started. Tried to log in, timed out. Checked the config and the ID was back at  2.

Either way, the ID is 2 on the client config as well, so there shouldn't be any disconnect. Any other ideas?

**Comment by lumien231** [comment]
Well there are no disconnects :P, there simply already is a dimension with the id of 2. 

Can you reproduce this with only rt installed?

**Comment by ajthemacboy** [comment]
Can't check right now, I'll let you know soon :)
