### ISSUE TITLE
Error when starting game from Dev Environment - java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by voidedWarranties** [lumien231/Random-Things#189]
I setup a Development Environment for this mod, on the same Forge (13.20.0.2216) and pressed the RUN button in Eclipse. It crashed on start, here's the log: [http://pastebin.com/KSy2R5zy](url)

Mac OS X 10.11.6 (El Capitan)
Eclipse Neon.2 Release 4.6.2
Forge 1.11.2 (13.20.0.2216)

**Comment by lumien231** [comment]
Random Things needs mcp mappings in a not obfuscated environment. Create a folder called mcp in your "main" project folder and copy fields.csv & methods.csv into it. You get those from [here](http://export.mcpbot.bspk.rs/).

**Comment by voidedWarranties** [comment]
It still didn't work.. So I copy fields.csv and methods.csv into the src/main/mcp folder? I also assume I need not the latest version, but the snapshot_20161220, as indicated by your build.gradle?

**Comment by lumien231** [comment]
No, the mcp folder has to be in the folder where your build.gradle file is. The best mapping version would be the one from your workspace yes.

**Comment by voidedWarranties** [comment]
Also, it appears that your item classes are throwing a java.lang.NullPointerException

Caused by: java.lang.NullPointerException
	at lumien.randomthings.item.ItemBottleOfAir.<clinit>(ItemBottleOfAir.java:35)
	... 45 more

**Comment by voidedWarranties** [comment]
Actually... java.lang.NoSuchFieldException: field_184128_aI 
Field does not exist?

**Comment by voidedWarranties** [comment]
In MCPNames.java, you state that mappingDir is "./../mcp", which is where?

Random-Things/
Random-Things/src/main/
Random-Things/src/main/java
Random-Things/src/main/java/lumien/randomthings

Or?

**Comment by lumien231** [comment]
These errors come from your missing mcp mappings. I already told you, the mcp folder has to be in the same folder where your build.gradle file is. (Or one directory up from your run directory).

**Comment by voidedWarranties** [comment]
It is in the same dir

**Comment by voidedWarranties** [comment]
![screen shot 2017-02-14 at 3 37 15 pm](https://cloud.githubusercontent.com/assets/14946719/22954477/878ec7e4-f2cb-11e6-9539-541a3640cc30.png)

**Comment by lumien231** [comment]
Could you post the content of the mcp folder?

**Comment by voidedWarranties** [comment]
![screen shot 2017-02-15 at 7 43 34 am](https://cloud.githubusercontent.com/assets/14946719/22981947/82e611c0-f352-11e6-8e5c-50e7b1f4e2a5.png)

**Comment by lumien231** [comment]
Huh, that's odd. Could you post your whole fml-client-latest log?

**Comment by voidedWarranties** [comment]
[http://pastebin.com/3GuAQHeZ](url)

Github doesn't support .log files

**Comment by lumien231** [comment]
You also need to add "-Dfml.coreMods.load=lumien.randomthings.asm.LoadingPlugin" to the VM Arguments of your Run Configuration (Run -> Run Configurations)

**Comment by voidedWarranties** [comment]
Thanks for your help! I really appreciate that you tried to help me through what I think is a time zone difference.
