### ISSUE TITLE
1.7.10 Spectre Missing

### ISSUE THREAD

**Issue by rcistano** [lumien231/Random-Things#19]
When I use the Spectre Key to get there all I do is fall and die. There are no walls or anything there.
There also seems to be weather patterns there. The last time I was there it was snowing and raining. There is also a building made of Bedrock about 50 blocks from where I would spawn into the Spectre Dimension.

**Comment by lumien231** [comment]
That's really odd, maybe try to change the spectre dimension id to something higher in the config file?

**Comment by rcistano** [comment]
OK, I will try that.

**Comment by rcistano** [comment]
Seems as though that worked, thanks.

**Comment by lumien231** [comment]
Nice :).

**Comment by rcistano** [comment]
Keep up the great work on these mods.
