### ISSUE TITLE
[1.11.2 - 3.7.9] Advanced Item Collector stops working

### ISSUE THREAD

**Issue by neoc666** [lumien231/Random-Things#190]
Not sure if I used it correctly because of the lack of documentation. I put it on the side of a vanilla single chest and configured 10x10x10 range. It works fine as long as I test it. But after leaving for a while and coming back much later, it doesn't work anymore. If I reinstall the collector in exactly the same way, it works again.

I guess it might be due to chunk unloading or something like that.

I'm teleporting quite often and this caused issues with pets - not sure if it is a problem in general which could be responsible for this issue.

Mod folder dump:

advInv-1.11.2-1.3.0.jar
BetterSprinting  MC-1.11.2  v1.1.9.jar
Chameleon-1.11-3.0.2.jar
cxlibrary-1.11.2-1.4.0.jar
hud-1.3.8-1.11.jar
jei_1.11.2-4.2.4.226.jar
LLOverlayReloaded-1.1.3-mc1.11.2.jar
OptiFine_1.11.2_HD_U_B6.jar
RandomThings-MC1.11.2-3.7.9.jar
StorageDrawers-1.11.2-4.1.0.jar
Xaeros_Minimap_1.12.2_Forge_1.11.jar
XaerosWorldMap_b1.8_Forge_1.11.jar

**Comment by lumien231** [comment]
Already fixed in 3.8

**Comment by neoc666** [comment]
Thank you!
