### ISSUE TITLE
[feature request] ingame descriptions on items

### ISSUE THREAD

**Issue by Zygus42** [lumien231/Random-Things#192]
Would be great to have a quick ingame description on each item, to save having to go to the wiki all the time.  Just a quick sentence about each one when holding the shift key would be more than enough, although an ingame guide book with pictures and such duplicating the wiki would be even better of course :)

**Comment by lumien231** [comment]
I'll probably add small descriptions to the info tab of JEI.

**Comment by xenxero1** [comment]
Reliquery does this very smoothly. I was kind of surprised this didn't just copy their system and paste in some lines from the wiki! Should be a very easy addition 👍
