### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Zekken01** [lumien231/Random-Things#194]
Your mod seems to be crashing the game.
1.10.2
https://paste.ee/p/Mz6Nu

**Comment by xenxero1** [comment]
this has been heavily reported already

**Comment by Zekken01** [comment]
oh, ok.

**Comment by lumien231** [comment]
So this stops happening when you remove Random Things?

**Comment by Zekken01** [comment]
yes

**Comment by lumien231** [comment]
Can you reproduce this with only Random Things installed?

**Comment by Zekken01** [comment]
no, It works fine on its own

**Comment by lumien231** [comment]
Could you find out with which mod it conflicts? Just keep removing half of your mods, shouldn't take long.

**Comment by Zekken01** [comment]
Sure thing

**Comment by Zekken01** [comment]
It's a mod called, The Betweenlands that doesn't work with it.

https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod?gameCategorySlug=mc-mods&projectID=243363

**Comment by Zekken01** [comment]
I got in touch with the Betweenlands dev and he said it was his mod causing the problem.
