### ISSUE TITLE
JSON model loader error FNF randomthings:models/block/platform.json

### ISSUE THREAD

**Issue by Syndaryl** [lumien231/Random-Things#199]
Stacktrace here:
https://gist.github.com/Syndaryl/0f4682d6a2392bfc5b31ccfc554e4c54

I'm getting this exception twice in my log on every game launch.

**Comment by lumien231** [comment]
On which rt version are you?

**Comment by Syndaryl** [comment]
3.7.9, downloaded on Feb 14. I see you updated two days later, sorry for missing that. I'll check 3.8 out.

**Comment by Syndaryl** [comment]
Fixed in 3.8 - my apologies.
