### ISSUE TITLE
Block breaker ignores inventories

### ISSUE THREAD

**Issue by Vectrobe** [lumien231/Random-Things#201]
According to the wiki (and what's generally expected), the block breaker will break blocks and place them into the inventory directly behind it, however this does not happen and instead the dropped item is dropped into the world directly in front of the breaker. Often for a cobble gen this results in the block jumping directly into the lava.

<img width="849" alt="screenshot_48" src="https://cloud.githubusercontent.com/assets/3912867/24785364/9dc4b31c-1b9c-11e7-8363-4855d3032954.png">

**Comment by lumien231** [comment]
The wiki contains the content for the latest RT version. It looks you might be playing Sky Factory which is on 1.10.2 ?

**Comment by Vectrobe** [comment]
version 3.7.7 on 1.10.2, yes

**Comment by lumien231** [comment]
Yeah, that functionality is only available from 3.8.1 onwards.

**Comment by Vectrobe** [comment]
Bit quick to jump to only 1.11 support aren't you...? pretty sure we wont see that as the mainstream for quite a while...

**Comment by lumien231** [comment]
I still "support" 1.10.2, if there were any game breaking bugs i would fix them. I just don't backport features.
