### ISSUE TITLE
Random Things 1.7.10 Bug With Pistons

### ISSUE THREAD

**Issue by KhOrganization** [lumien231/Random-Things#21]
Dear Lumien231,
I got this mod mainly for the wireless lever, and I primarily wanted to use it for pistons. When I got the mod I was disappointed that this worked with everything I tested but pistons. So I wanted to let you know about this problem, and was wondering if you can fix this.
Thanks in advance.
-KhOrganization

**Comment by lumien231** [comment]
Sorry but there are no 1.7.10 updates anymore :/.
