### ISSUE TITLE
Cascading worldgen lag?

### ISSUE THREAD

**Issue by Endmateria** [lumien231/Random-Things#210]
Hey lumien, I'm getting a couple hits of cascading worldgen lag from your mod.  Though it naturally happens when I explore the world without Structpro installed, in this short log I'm using structpro to pre-generate world chunks in a new world from the server console (nobody ingame).  https://gist.github.com/Endmateria/99b4a59ebcdb10e1c0abcb2195142f4b#file-fml-server-latest-log  Which amounts to this occurring during worldgen....  https://ibb.co/mwFtMQ

I don't know what the issue is cuz your mod really doesn't spawn that much in the world... possibly the crystal spawn areas (those are the largest)?  I can get you a full log of it happening ingame if you want (though it wouldn't be much different than the log above).  It would just report cascading worldgen lag as I fly around opening up new chunks.  Assuming that it's not another mod causing your mod to behave like this (I can send you a modlist if necessary), then Mezz (from JEI and Forestry) seems to know all about how to resolve it...  https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

MC 1.11.2
RT 3.8.1
Forge 2294

**Comment by Endmateria** [comment]
Here's another detailed link/discussion on the subject...  https://github.com/Vazkii/Quark/issues/412

**Comment by lumien231** [comment]
Could you try disabling the Worldgen Options to see what is causing it? The only thing that could overlap into other chunks is the Nature Core and that should already be fixed.

**Comment by Endmateria** [comment]
Well there were some false solutions for this issue floating around, notably capnkirok who said that the "Fix appears to be to offset your worldgen point to be the center of the chunk... so offset 8 to x and z coordinates so the world gen starts at the center and moves out. Otherwise you overlap with already generated chunks."  This got called out on the Quark thread as a false solution.  Anyways, if you're sure your worldgen is right, then yeah, I can run some tests.  It's not getting a lot of hits during pregen, but then again you don't have a lot of blocks generating, just the nature cores (I think I was confusing your mod with Quark in regards to the crystal generation).  But regardless, I can start a fresh world and run an "RT only" pregen if you'd like.  I can also run a pregen with certain RT worldgen options disabled (or all) if you'd like.  I'll start troubleshooting on it as soon as my current world is done generating.

**Comment by Endmateria** [comment]
K, I ran some tests with only your mod installed, using the same seed with fresh world maps each run, while pre-generating 10,000 chunks per run.

When all gen configs true=9 hits
When all gen configs false=0 hits
Only nature core true=0 hits
Only water chest true=0 hits
Only beans true=14 hits
Only pitcherplants true=1 hit
Only biome crystal,lava charm,magic hood,summoning pendulum true=0 hits
Only sakanade true=0 hits

**Comment by Endmateria** [comment]
Mezz stated in another thread that "I wouldn't trust pre-generators, they tend to add optimizations for speed that make them potentially unreliable for this kind of test. I just load up a creative world and fly in a straight line."  Given this fact, and the fact that the Structpro pre-generator is incredibly unreliable (I have since removed it from my mod list), I'll close this issue for now and keep an eye on my logs for any RT worldgen issues.  As you said in so many words, it doesn't seem like single block gen (like the beans and pitcher plants) should be causing worldgen lag.

**Comment by lumien231** [comment]
I did get the same messages while flying around in a creative world. Fixed them for the next version.

**Comment by Endmateria** [comment]
Gotcha, hey if you're working on the next update, you may also want to check the beetroot seeds when growing on fertilized dirt.  I couldn't get the seeds to stay planted, regardless of how I adjusted the lighting... they kept popping up.  Haven't had a problem planting any of the other crops (vanilla or modded) so I thought that was strange.  I haven't gotten around to removing other mods or general troubleshooting yet, but I thought I'd throw that out there if you're currently working on the next update.

**Comment by lumien231** [comment]
Will be fixed as well :).
