### ISSUE TITLE
[1.10.2] Feature request: Shield Slot on Player Interface

### ISSUE THREAD

**Issue by pdohogne** [lumien231/Random-Things#220]
The Shield/Offhand slot exists in MC 1.10.2, but the player interface is missing the capability to interact with it as it has in 1.11.  Is there a reason for this, or can it be added?  Currently it's the only slot in the player's inventory that can't be interacted with.

**Comment by lumien231** [comment]
1.10.2 doesn't get gameplay updates anymore so that's why it's not available there.
