### ISSUE TITLE
Can't craft most items in Minecraft 1.12

### ISSUE THREAD

**Issue by lainy** [lumien231/Random-Things#221]
Unable to craft almost any Random Things in 1.12.
Can craft the custom workbenches and maybe a couple other things. The rest can only be obtained via creative mode.

Guessing it's because a lot seems to be missing from [ModRecipes.java](https://github.com/lumien231/Random-Things/blob/master/src/main/java/lumien/randomthings/recipes/ModRecipes.java)?

EDIT: I also tried adding JEI to the server, and it only shows Information for the things I can't craft (Analog Emitter, Lapis Glass, etc etc everything else), doesn't show a recipe.

**Comment by lumien231** [comment]
Like it says in the release notes of the version a forge bug is currently preventing recipes from loading in non-dev environments.
