### ISSUE TITLE
crash with Tough As Nails and Extra Utilities

### ISSUE THREAD

**Issue by 0Navis0** [lumien231/Random-Things#224]
I link this issue here because Random Things seems to be linked to it. https://github.com/Glitchfiend/ToughAsNails/issues/274

**Comment by lumien231** [comment]
Yeah, i already fixed this in 1.12. Might make another version for 1.11.2 then.

**Comment by 0Navis0** [comment]
Yeah it would be really nice you fix it for 1.11.2 too. ;)
