### ISSUE TITLE
[1.12][4.0.3] Worldgen in SuperFlat world type

### ISSUE THREAD

**Issue by Kris1432** [lumien231/Random-Things#228]
Forge: 2405
Version: 4.0.3

Generate Structures is turned off yet Random Things' Plants spawn in the world.

Picture: https://puu.sh/wNOsj.png

**Comment by xenxero1** [comment]
I uh, I dont think plants count as structures?

**Comment by Kris1432** [comment]
doesn't matter. they still shouldn't spawn in this world setting.

**Comment by lumien231** [comment]
Vanilla also generates plants with generate structures turned off so rt will as well. Might remove them from the super flat world type.

**Comment by Kris1432** [comment]
see here: https://github.com/ForestryMC/ForestryMC/issues/1760#issuecomment-316804873
