### ISSUE TITLE
Constant crashing after using biome painter.

### ISSUE THREAD

**Issue by tristanrussell2000** [lumien231/Random-Things#23]
In my SSP world, I was trying to use the biome capsule/painter to change the biome of one of my bases. After using the painter, nothing happened for a while, and then suddenly I crashed to desktop. After, every time I log into the world, it crashes after 5-10 seconds of being in the world. If it helps, I was trying to convert a plains biome into a RTG Highlands biome. 

I was able to replicate this, I created a new creative world, spawned in the biome tools, and tried to convert a plains into a beach biome. A minute or two after using the painter, it crashed with the same error.

Here is the error: http://openeye.openmods.info/crashes/35e992f4eb73cdf6d346a79584dba233

I have tried deleting Random Things, deleting the random thing.dat from my world, and deleting the affected chunks in MCEdit, none of which have worked.

**Comment by lumien231** [comment]
Presumably this doesn't happen with only Random Things installed. Could you check with which mods it happens?

**Comment by tristanrussell2000** [comment]
I seem to have fixed the issue by updating DragonAPI to the latest version, v8e. However, I was having no problems whatsoever with v8d before using the biome painter.

**Comment by lumien231** [comment]
Well if it's fixed i'll close this^^.
