### ISSUE TITLE
1.12 Crash by using the Advanced Item Collector with filter

### ISSUE THREAD

**Issue by Jasoncrazy01** [lumien231/Random-Things#234]
I was using the Advanced Item Collector to pick up items by autocrafting fluix crystals by Applied Llamagistics and set the filter only to suck up fluix crystals. By throwing the components into a puddle of water it crashed.
[crash-2017-08-03_16.45.10-server.txt](https://github.com/lumien231/Random-Things/files/1197579/crash-2017-08-03_16.45.10-server.txt)

**Comment by lumien231** [comment]
For now don't use the ore dict option in the item filter.
