### ISSUE TITLE
Error with OpenComputers

### ISSUE THREAD

**Issue by ZephaniahNoah** [lumien231/Random-Things#238]
```
[16:38:58] [main/WARN] [OpenComputers/randomthings]: Failed injecting component logic into class lumien.randomthings.tileentity.TileEntityCreativePlayerInterface.
li.cil.oc.common.asm.ClassTransformer$InjectionFailedException: Found SimpleComponent on something that isn't a tile entity, ignoring.
```
It also says this in chat when a world is opened:
"OpenComputers: An addon (yours?) using the SimpleComponent interface did something wrong. Component logic could not be injected. Please check your log file for more information."

**Comment by brisingraerowing** [comment]
The SimpleComponent error was a bug in OC itself. The latest CI build has a fix for it.
