### ISSUE TITLE
Crashing on World Loading, only happens when I add Random Things.

### ISSUE THREAD

**Issue by ghost** [lumien231/Random-Things#24]
[Here's the crash report](http://paste.ee/p/0H9yQ)

As I said, this only occurs when I add Random Things in the modpack. Is this some kind of weird incompatibility with MapWriter/Opis? I know those two worked together before.

**Comment by capSAR273** [comment]
I am having the same issue with Infinity, and the latest version of Random things for 1.7.10 (2.2.4). Only thing is it doesn't generate a crash report, just the log here: http://paste.ee/p/GJEqk

**Comment by lumien231** [comment]
@capSAR273 Remove Fast Leaf Decay, it's included in random things.

**Comment by capSAR273** [comment]
@lumien231 I feel silly I missed that, thank you!
