### ISSUE TITLE
[1.12] Crash with item rendering in JEI 4.7.10.99

### ISSUE THREAD

**Issue by mezz** [lumien231/Random-Things#242]
In the latest JEI, I am drawing items to my own buffer instead of using the `Tesselator`'s.
You have some injected code that assumes the `Tesselator` is running and calls `.draw()`, which crashes ([crash log](https://gist.github.com/mezz/545e167d624ac2931d59921ad64cda6b)):

https://github.com/lumien231/Random-Things/blob/ae1b9550c222ee6c982105d0bc233a6d3f9103b0/src/main/java/lumien/randomthings/handler/LuminousHandler.java#L39-L61

Please grab the `Tesselator`'s buffer and check if `BufferBuilder#isDrawing` before stopping it.
I'm also not entirely sure if your rendering will work with JEI's new rendering.
If you switch to use `bakedModel.isBuiltInRenderer()` it will not go through any of JEI's optimizations.

Normally I would work around this issue on my side, but since you are using assembly here to change the logic in a place that's not normally possible, I hope it's fair to ask for the fix. Thanks!

**Comment by IchigoGames** [comment]
got the same crash
