### ISSUE TITLE
[1.12.2] Crash with latest JEI version

### ISSUE THREAD

**Issue by TheLimePixel** [lumien231/Random-Things#245]
When looking for something from Random Things in JEI, the client crashes:
https://pastebin.com/29yChzjj

**Comment by Zedrimar** [comment]
I can confirm this and can narrow it down to the luminous blocks

**Comment by Zedrimar** [comment]
funny enough, NEI doesn't make it crash but JEI viewing mode WILL crash it

**Comment by lumien231** [comment]
Duplicate of #242
