### ISSUE TITLE
Just FYI

### ISSUE THREAD

**Issue by Fortist** [lumien231/Random-Things#25]
I know you're not keeping up with 1.7.10, even if its superior to 1.8 in all, but your mod has an outdated COFH API, which breaks something somewhere unless you delete it from the .jar.
My game doesnt even start up when it was in.

Also, the energy routers kinda suck. 100 RF per tick is pretty garbage.

**Comment by lumien231** [comment]
Just FYI "which breaks something somewhere" is not a bug report. I just loaded up the latest Thermal Expansion together with RandomThings in 1.7.10, the Energy Distributor (If that's what you mean is broken) seems to work fine. Random Things should always use the latest RF API a mod has included that is currently loaded. If you crash, post a crash report. 

Well they are meant to power many small things. If i ever remake them i will probably add some sort of upgrade system though. 

And no, the MC Version 1.7.10 is not superior to the 1.8 version. The amount of mods for 1.7.10 compared to 1.8 is.
