### ISSUE TITLE
Entity Detector Range not applied properly

### ISSUE THREAD

**Issue by Knito58** [lumien231/Random-Things#250]
MC 1.12.2, Forge 14.23.0.2503, Random Things 4.0.6.1, Gamemode SSP

I understand the radius as a value which is applied to the entity detector which is put in the center of the so surveilled 3d room. But the radius value applied in the entity detector's GUI only works in one direction. Seems as if only the positive x or z value is added. From the other side: Nothing. So the detector acts strangely depending on the direction from where the entity comes.

And a big whish / suggestion:

The detector only gives out a redstone signal if redstone is attached to it. I would like to see the block being redstone-ON or redstone-OFF instead of this. With strength 16, of course. This would allow much smaller door opening constructions.

**Comment by lumien231** [comment]
The issue was already fixed in 839875ce, will add a new Button to the GUI to Switch between Strong and Weak Redstone Power :).

**Comment by Knito58** [comment]
Thank you.

**Comment by Knito58** [comment]
Wow! Great!
I love this.
