### ISSUE TITLE
minecraft wont load

### ISSUE THREAD

**Issue by sirzento** [lumien231/Random-Things#251]
I added some mods to the ftb pack infinity evolved and it just work finde but if I add random things to it, it will say "unable to load" in the minecraft launcher when I start minecraft.

Here is the log: https://pastebin.com/HniEk8zN

**Comment by lumien231** [comment]
Random Things and Fast Leaf Decay aren't compatible because Random Things comes with its own fast leaf decay. Remove Fast Leaf Decay.
