### ISSUE TITLE
Add a Global Chat Detector?

### ISSUE THREAD

**Issue by SirMoogle** [lumien231/Random-Things#259]
I tried out the Chat Detector and I enjoyed it. Is there any thought about adding a Global Chat Detector, or a Chat Detector that detects all players instead of just the one who placed it in the world?

**Comment by lumien231** [comment]
Sure, will work like the normal Chat Detector except for all players. Will make it require an id card for the "consume" mode so you can't just prevent other players from typing stuff in chat without their permission.
