### ISSUE TITLE
Random Things and Quark fight one another.

### ISSUE THREAD

**Issue by Akitori** [lumien231/Random-Things#269]
Long story short, quark seems to disable random thing's glowing enchantments on items but not on armor, this goes with the coloring of weapons as well.

Video proof:

https://youtu.be/DAFE5NIu1hw

**Comment by lumien231** [comment]
I've already fixed this from the rt side :). (https://github.com/lumien231/Random-Things/commit/85fa23f3dbc07de2bd3489592dc2a4fa8bb04312), it just still has to be fixed on Quarks side. Here's the issue for that: https://github.com/Vazkii/Quark/issues/724

**Comment by Akitori** [comment]
As a note: apparently colored items don't work due to a optifine issue rather than anything on quark's end.
