### ISSUE TITLE
Crash involving fluid display

### ISSUE THREAD

**Issue by Newton10** [lumien231/Random-Things#27]
I right clicked the fluid display with a bucket of water and I crashed, I had to go into MC Edit to get rid of the block and reload the world, so here's the crash report so it can get fixed.

http://pastebin.com/h5xfM9KZ

**Comment by lumien231** [comment]
Could you try to update your forge to the latest version?

**Comment by Newton10** [comment]
alright I'll try that tonight, just tried the recommended version when i did the original download.
