### ISSUE TITLE
1.12.2 - 4.1.1 Villager Trading Broken

### ISSUE THREAD

**Issue by Endmateria** [lumien231/Random-Things#281]
After installing your newest update 1.12.2 -4.1.1, I was no longer able to right click on villagers i.e., the trading menu no longer opens (all vanilla and modded villagers are affected).  I isolated it down to this mod, all other mods have been removed with the exception of Forge itself.

MC 1.12.2
Forge 1.12.2 - 14.23.1.2589 (latest)
Random Things 1.12.2 -4.1.1

**Comment by DoragonKeiyou** [comment]
Also seeing this issue with above versions, forge is .2577 though.
