### ISSUE TITLE
1.10.2 Spectre Anchor - Anchored Modifier not working

### ISSUE THREAD

**Issue by Aiidoneus** [lumien231/Random-Things#284]
https://github.com/lumien231/Random-Things/issues/171

I looked through the issues and found this one similar to my issue on my server. To simplify everything, the gravestone mod cancels out the anchor it seems. 

This is the gravestone mod https://minecraft.curseforge.com/projects/gravestone-mod
Version of Random Things RandomThings-MC1.10.2-3.7.7.1.jar

**Comment by lumien231** [comment]
It probably is that issue, it was fixed in 1.11 and i generally don't update older rt versions unless there are critical world breaking issues.
