### ISSUE TITLE
Spectre Anchor duplicates Items

### ISSUE THREAD

**Issue by def0jay** [lumien231/Random-Things#287]
RandomThings-MC1.12.2-4.1.2 
Forge: 14.23.1.2590 
Pack: Modern Skyblock 2

Pretty much what the Title says. Anchored Items will be duplicated after death.

**Comment by lumien231** [comment]
Can you reproduce this with only rt installed? How do they duplicate? Do you get additional copies in your inventory after respawning?

**Comment by def0jay** [comment]
Ok, seems to be an Interaction with Corail Tombstone 2.3.0-1.12.  I could only replicate it with this Version added. With the new Version of Corail Tombstone it dosen't happen anymore.
