### ISSUE TITLE
[1.10.2] A bunch of model glitches

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [lumien231/Random-Things#291]
I dun know if it is neccessarily RT's bug, however this log involves many different mods , I would like to know what is happening

Apparently the client freezes from the last log, `ieScaffolding` and can no longer resume loading textures

https://gist.github.com/Pythonic-Rainbow/9269a0e88312f3087ff3df67091bf060

**Comment by lumien231** [comment]
I don't think this has anything to do with Random Things, try to keep removing mods till it works again.

**Comment by Pythonic-Rainbow** [comment]
Well , it isn't really a bug , just notifying you that some models seems to have glitched in stage 7.
Anyways my problem has solved by just simply restart the client.Weird
