### ISSUE TITLE
Can't launcher minecraft

### ISSUE THREAD

**Issue by ghost** [lumien231/Random-Things#30]
download this mod and I can't launcher minecraft now , I have downloaded:EnchantView , IndustrialCraft2 , ThebombzenAPI , Better Furnaces , deconstruction , myfit , advancedcapes , AdvancedSolarPanel , AppleCore , Applied Energistics2 , Baubles , BigReactors , Botania , BuildCraft , Chest Transporter , ChickenChunks , CodeChickenCore , CoFHCore , Draconic Evolution , EbderCore , EnderIO , EnderIOAddons , EnderStorage , Ex Astris , Ex Nihilo , Extra Utilities , FastCraft , FastLeafDecay , FortuneOres , GravityGun , Hardcore Wither . iChunUtil , Inventory Tweaks , Iron Backpacks , Ironchest , Jabba , KeepingInventory , LootBags , Lucky block , Mantle , MineFactoryReloaded , MultiPageChest , NotEnoughItems , OpenBlocks , OpenModsLib , OptiFine , OreDictionnaryConverter , PlanterHelper , Plants To Ores , RandomThing , RedstoneArsenal , ReisMinimap . SimplyJetpacks , SolarExpanison , SolarFlux , SuperMultiDrills , TiC  , ThermalDynamics , ThermalExpansion , ThermalFoundation , ThermalSmeltey , Torcherino , VeinMiner , Waila , WailaHarvestability 1.7.10 mods

**Comment by lumien231** [comment]
Crash log?

**Comment by ghost** [comment]
when I opening game launcher are missing , so.... I think no any crash log

**Comment by lumien231** [comment]
There is one, which launcher are you using?

**Comment by ghost** [comment]
Shiginima Launcher

**Comment by ghost** [comment]
when I playing minecraft with only RandomThings mod , it's working

**Comment by lumien231** [comment]
There IS a crash log, no idea about your launcher (Because it's cracked :P) but they have to be stored somewhere.

**Comment by ghost** [comment]
I am finding my crash log...

**Comment by ghost** [comment]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2015/11/11 下午 11:51
Description: Registering texture

java.lang.OutOfMemoryError: Java heap space
    at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:257)
    at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:248)
    at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:199)
    at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:48)
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94)
    at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:50)
    at net.minecraft.client.gui.achievement.GuiAchievement.func_146254_a(SourceFile:101)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1030)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:257)
    at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:248)
    at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:199)
    at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:48)

-- Resource location being registered --
Details:
    Resource location: minecraft:textures/gui/achievement/achievement_background.png
    Texture object class: net.minecraft.client.renderer.texture.SimpleTexture
Stacktrace:
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94)
    at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:50)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['alxan_vance'/94876, l='MpServer', x=1696.43, y=65.62, z=17701.08]]
    Chunk stats: MultiplayerChunkCache: 169, 178
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (220,64,244), Chunk: (at 12,4,4 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 2972937 game time, 1153424 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 89 total; [EntityBat['Bat'/94976, l='MpServer', x=1622.50, y=38.00, z=17698.25], EntitySkeleton['Skeleton'/95875, l='MpServer', x=1633.13, y=33.00, z=17764.53], EntityPig['Pig'/94853, l='MpServer', x=1771.13, y=71.00, z=17633.84], EntitySkeleton['Skeleton'/95749, l='MpServer', x=1631.50, y=31.00, z=17705.50], EntityCreeper['Creeper'/95876, l='MpServer', x=1635.50, y=36.00, z=17752.50], EntityZombie['Zombie'/95764, l='MpServer', x=1652.75, y=44.00, z=17747.75], EntityFireworkRocket['entity.FireworksRocketEntity.name'/96281, l='MpServer', x=1696.50, y=66.63, z=17700.50], EntitySheep['Sheep'/94872, l='MpServer', x=1629.47, y=73.00, z=17779.09], EntitySkeleton['Skeleton'/95902, l='MpServer', x=1774.50, y=15.00, z=17664.50], EntityCreeper['Creeper'/95009, l='MpServer', x=1625.44, y=43.00, z=17693.56], EntityCreeper['Creeper'/95008, l='MpServer', x=1620.50, y=23.00, z=17668.50], EntitySkeleton['Skeleton'/95011, l='MpServer', x=1622.03, y=23.00, z=17670.97], EntitySkeleton['Skeleton'/95907, l='MpServer', x=1617.50, y=27.00, z=17703.50], EntityCreeper['Creeper'/95906, l='MpServer', x=1658.50, y=30.00, z=17680.50], EntityCreeper['Creeper'/95909, l='MpServer', x=1656.50, y=30.00, z=17677.50], EntitySpider['Spider'/95012, l='MpServer', x=1752.16, y=18.00, z=17677.63], EntityZombie['Zombie'/95908, l='MpServer', x=1623.50, y=23.00, z=17671.50], EntitySpider['Spider'/95014, l='MpServer', x=1707.50, y=20.00, z=17646.50], EntityEnderman['Enderman'/94888, l='MpServer', x=1640.41, y=32.00, z=17685.63], EntityZombie['Zombie'/95018, l='MpServer', x=1661.50, y=29.00, z=17706.50], EntityClientPlayerMP['alxan_vance'/94876, l='MpServer', x=1696.43, y=65.62, z=17701.08], EntityCreeper['Creeper'/95023, l='MpServer', x=1626.41, y=43.00, z=17693.00], EntityWitch['Witch'/95022, l='MpServer', x=1659.16, y=46.00, z=17741.50], EntityCreeper['Creeper'/94897, l='MpServer', x=1764.50, y=46.00, z=17631.50], EntityBat['Bat'/94901, l='MpServer', x=1621.63, y=31.00, z=17711.88], EntityChicken['Chicken'/94775, l='MpServer', x=1696.44, y=70.00, z=17702.28], EntityZombie['Zombie'/95801, l='MpServer', x=1728.50, y=26.00, z=17635.50], EntityItem['item.item.egg'/94776, l='MpServer', x=1696.88, y=70.13, z=17702.13], EntityCreeper['Creeper'/94904, l='MpServer', x=1766.50, y=46.00, z=17631.50], EntitySkeleton['Skeleton'/95805, l='MpServer', x=1630.50, y=31.00, z=17705.50], EntitySkeleton['Skeleton'/95804, l='MpServer', x=1630.50, y=31.00, z=17703.50], EntitySheep['Sheep'/94783, l='MpServer', x=1692.91, y=64.00, z=17648.16], EntitySkeleton['Skeleton'/95811, l='MpServer', x=1645.50, y=14.00, z=17717.50], EntityEnderman['Enderman'/94917, l='MpServer', x=1667.63, y=15.00, z=17649.13], EntitySkeleton['Skeleton'/96069, l='MpServer', x=1621.50, y=40.00, z=17668.50], EntityCreeper['Creeper'/94918, l='MpServer', x=1633.50, y=30.00, z=17652.50], EntityZombie['Zombie'/96070, l='MpServer', x=1756.45, y=16.69, z=17671.70], EntitySquid['Squid'/95817, l='MpServer', x=1659.53, y=62.31, z=17716.50], EntitySquid['Squid'/95819, l='MpServer', x=1660.28, y=62.38, z=17723.59], EntitySquid['Squid'/95818, l='MpServer', x=1660.13, y=62.34, z=17714.19], EntitySquid['Squid'/95821, l='MpServer', x=1639.28, y=58.25, z=17677.22], EntitySquid['Squid'/95820, l='MpServer', x=1658.06, y=61.31, z=17721.03], EntitySquid['Squid'/95823, l='MpServer', x=1645.38, y=59.28, z=17682.09], EntitySquid['Squid'/95822, l='MpServer', x=1641.50, y=58.00, z=17674.53], EntityZombie['Zombie'/95825, l='MpServer', x=1638.50, y=34.00, z=17759.50], EntityPig['Pig'/94800, l='MpServer', x=1730.09, y=71.00, z=17764.91], EntitySquid['Squid'/95824, l='MpServer', x=1638.50, y=60.34, z=17671.50], EntityBat['Bat'/95827, l='MpServer', x=1744.75, y=57.00, z=17633.63], EntityBat['Bat'/95826, l='MpServer', x=1743.63, y=57.00, z=17630.59], EntityPig['Pig'/94807, l='MpServer', x=1740.22, y=67.00, z=17730.34], EntityTrail['unknown'/95062, l='MpServer', x=1696.43, y=65.62, z=17701.08], EntityBat['Bat'/95833, l='MpServer', x=1662.38, y=21.78, z=17699.73], EntityZombie['Zombie'/94939, l='MpServer', x=1664.50, y=29.00, z=17677.50], EntitySheep['Sheep'/94811, l='MpServer', x=1766.16, y=65.00, z=17675.84], EntityCreeper['Creeper'/94938, l='MpServer', x=1651.50, y=29.00, z=17677.50], EntityPig['Pig'/94810, l='MpServer', x=1642.44, y=65.00, z=17639.91], EntityBat['Bat'/95834, l='MpServer', x=1628.47, y=30.00, z=17770.50], EntitySheep['Sheep'/94813, l='MpServer', x=1686.94, y=70.00, z=17774.50], EntityCreeper['Creeper'/94941, l='MpServer', x=1625.50, y=29.00, z=17779.50], EntitySkeleton['Skeleton'/95837, l='MpServer', x=1738.50, y=57.00, z=17629.50], EntitySkeleton['Skeleton'/96093, l='MpServer', x=1620.50, y=40.00, z=17669.50], EntitySheep['Sheep'/94812, l='MpServer', x=1638.06, y=66.00, z=17756.16], EntityCreeper['Creeper'/95838, l='MpServer', x=1635.50, y=34.00, z=17759.50], EntitySkeleton['Skeleton'/96094, l='MpServer', x=1622.50, y=40.00, z=17668.50], EntityPig['Pig'/94821, l='MpServer', x=1755.72, y=64.00, z=17689.16], EntityZombie['Zombie'/94949, l='MpServer', x=1667.50, y=23.00, z=17738.50], EntityPig['Pig'/94820, l='MpServer', x=1752.22, y=74.00, z=17705.50], EntitySheep['Sheep'/94823, l='MpServer', x=1654.50, y=73.00, z=17767.50], EntityCreeper['Creeper'/94951, l='MpServer', x=1650.50, y=40.00, z=17764.50], EntitySkeleton['Skeleton'/94950, l='MpServer', x=1666.50, y=23.00, z=17737.50], EntityZombie['Zombie'/94825, l='MpServer', x=1638.69, y=44.35, z=17678.74], EntitySheep['Sheep'/94824, l='MpServer', x=1657.47, y=69.00, z=17774.53], EntityBat['Bat'/94955, l='MpServer', x=1662.51, y=18.29, z=17688.59], EntityChicken['Chicken'/94826, l='MpServer', x=1638.69, y=44.00, z=17678.84], EntitySkeleton['Skeleton'/94958, l='MpServer', x=1753.50, y=16.00, z=17667.91], EntityBat['Bat'/94961, l='MpServer', x=1619.50, y=39.82, z=17690.50], EntityCow['Cow'/94837, l='MpServer', x=1671.31, y=63.00, z=17683.07], EntityCow['Cow'/94836, l='MpServer', x=1671.32, y=63.00, z=17684.32], EntityCow['Cow'/94839, l='MpServer', x=1668.09, y=63.00, z=17686.09], EntityCow['Cow'/94838, l='MpServer', x=1672.91, y=63.00, z=17683.09], EntityCow['Cow'/94841, l='MpServer', x=1669.19, y=63.00, z=17687.03], EntityCow['Cow'/94840, l='MpServer', x=1668.09, y=63.00, z=17687.50], EntityCow['Cow'/94843, l='MpServer', x=1669.28, y=63.00, z=17688.34], EntitySkeleton['Skeleton'/95867, l='MpServer', x=1743.50, y=57.00, z=17629.50], EntityCow['Cow'/94842, l='MpServer', x=1670.07, y=63.00, z=17683.09], EntityCow['Cow'/94844, l='MpServer', x=1670.09, y=63.00, z=17684.41], EntitySkeleton['Skeleton'/95868, l='MpServer', x=1639.66, y=34.00, z=17762.66], EntityBat['Bat'/94975, l='MpServer', x=1628.75, y=28.00, z=17685.50], EntitySheep['Sheep'/94847, l='MpServer', x=1763.63, y=70.00, z=17626.22]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 23930736 bytes (22 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 77 mods loaded, 77 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAAAAAAA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAAAAAAA  Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAAAAAAA  appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAAAAAAA  CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAAAAAAA  NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJAAAAAAAAA  VeinMiner_coremod{null_build-null} [Core mod](minecraft.jar) 
    UCHIJAAAAAAAAA  OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UCHIJAAAAAAAAA  <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAAAAAAA  myfit{1.8.4} [MyFit](1.7.10-myfit-1.8.4.jar) 
    UCHIJAAAAAAAAA  FLabsBF{4.3} [Better Furnaces]([1.7.10]Better_Furnaces_V4.3.jar) 
    UCHIJAAAAAAAAA  deconstruction{2.2.5} [The Deconstruction Mod]([MC1.7.10]deconstruction[v2.2.5].jar) 
    UCHIJAAAAAAAAA  advancedcapes{1.4} [AdvancedCapes Mod](advancedcapes-1.4.jar) 
    UCHIJAAAAAAAAA  IC2{2.2.791-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.791-experimental.jar) 
    UCHIJAAAAAAAAA  AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) 
    UCHIJAAAAAAAAA  AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) 
    UCHIJAAAAAAAAA  appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJAAAAAAAAA  CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAAAAAAA  BuildCraft|Core{7.0.25} [BuildCraft](buildcraft-7.0.25.jar) 
    UCHIJAAAAAAAAA  BuildCraft|Builders{7.0.25} [BC Builders](buildcraft-7.0.25.jar) 
    UCHIJAAAAAAAAA  BuildCraft|Transport{7.0.25} [BC Transport](buildcraft-7.0.25.jar) 
    UCHIJAAAAAAAAA  BuildCraft|Energy{7.0.25} [BC Energy](buildcraft-7.0.25.jar) 
    UCHIJAAAAAAAAA  BuildCraft|Silicon{7.0.25} [BC Silicon](buildcraft-7.0.25.jar) 
    UCHIJAAAAAAAAA  BuildCraft|Robotics{7.0.25} [BC Robotics](buildcraft-7.0.25.jar) 
    UCHIJAAAAAAAAA  BuildCraft|Factory{7.0.25} [BC Factory](buildcraft-7.0.25.jar) 
    UCHIJAAAAAAAAA  ChestTransporter{1.1.10} [Chest Transporter](Chest-Transporter-Mod-1.7.10.jar) 
    UCHIJAAAAAAAAA  ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHIJAAAAAAAAA  CraftableAnimals{2.4.3.0} [Craftable Animals](Craftable-Animals-Mod-1.7.10.jar) 
    UCHIJAAAAAAAAA  ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAAAAAAA  ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJAAAAAAAAA  DraconicEvolution{1.0.1c} [Draconic Evolution](Draconic-Evolution-1.7.10-1.0.1c.jar) 
    UCHIJAAAAAAAAA  thebombzenapi{2.4.1} [ThebombzenAPI](ThebombzenAPI-v2.4.1-mc1.7.2.jar) 
    UCHIJAAAAAAAAA  enchantview{4.0.4} [EnchantView](EnchantView-Mod-1.7.10.jar) 
    UCHIJAAAAAAAAA  endercore{1.7.10-0.2.0.30_beta} [EnderCore](EnderCore-1.7.10-0.2.0.30_beta.jar) 
    UCHIJAAAAAAAAA  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAAAAAAA  EnderIO{1.7.10-2.3.0.417_beta} [Ender IO](EnderIO-1.7.10-2.3.0.417_beta.jar) 
    UCHIJAAAAAAAAA  enderioaddons{1.7.10-2.3.0.417_beta-0.6.0.011_beta} [Ender IO Addons](EnderIOAddons-1.7.10-2.3.0.417_beta-0.6.0.011_beta.jar) 
    UCHIJAAAAAAAAA  EnderStorage{1.4.7.33} [EnderStorage](EnderStorage-1.7.10-1.4.7.33-universal.jar) 
    UCHIJAAAAAAAAA  exnihilo{1.38-46} [Ex Nihilo](Ex-Nihilo-1.38-46.jar) 
    UCHIJAAAAAAAAA  RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
    UCHIJAAAAAAAAA  ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAAAAAAA  ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHIJAAAAAAAAA  Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHIJAAAAAAAAA  TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct](TConstruct-1.7.10-1.8.7.jar) 
    UCHIJAAAAAAAAA  exastris{MC1.7.10-1.16-36} [Ex Astris](Ex-Astris-MC1.7.10-1.16-36.jar) 
    UCHIJAAAAAAAAA  FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJAAAAAAAAA  fastleafdecay{1.0} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.0.jar) 
    UCHIJAAAAAAAAA  FortuneOres{2.0.5} [FortuneOres](FortuneOres-MC1.7.10-2.0.5.jar) 
    UCHIJAAAAAAAAA  iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHIJAAAAAAAAA  GraviGun{4.0.0-beta} [GraviGun](GravityGun-4.0.0-beta.jar) 
    UCHIJAAAAAAAAA  hardcorewither{1.0.0} [Hardcore Wither](Hardcore Wither-1.7.10-1.0.0-3-universal.jar) 
    UCHIJAAAAAAAAA  inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](Inventory-Tweaks-Mod-1.7.10.jar) 
    UCHIJAAAAAAAAA  ironbackpacks{0.5.0} [Iron Backpacks](Iron Backpacks-1.7.10-1.0.4-universal.jar) 
    UCHIJAAAAAAAAA  IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAAAAAAA  JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAAAAAAA  KeepingInventory{1.1} [Keeping Inventory](KeepingInventory-1.7.10-1.1.jar) 
    UCHIJAAAAAAAAA  lootbags{1.8.1} [Loot Bags](LootBags-1.7.10-1.8.1.jar) 
    UCHIJAAAAAAAAA  lucky{5.1.0} [Lucky Block](Lucky-Block-Mod-1.7.10.jar) 
    UCHIJAAAAAAAAA  MultiPageChest{1.3.4} [Multi Page Chest](MultiPageChest-1.3.4-MC1.7.10.jar) 
    UCHIJAAAAAAAAA  OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    UCHIJAAAAAAAAA  OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4-snapshot-652.jar) 
    UCHIJAAAAAAAAA  fodc{1.6.1} [Ore Dictionary Converter](OreDictionaryConverter-1.6.1.jar) 
    UCHIJAAAAAAAAA  PlanterHelper{0.5.0} [Planter Helper](PlanterHelper-1.7.10_0.5.0.jar) 
    UCHIJAAAAAAAAA  plo{1.0} [plo](Plants-To-Ores V1.0.jar) 
    UCHIJAAAAAAAAA  ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) 
    UCHIJAAAAAAAAA  simplyjetpacks{1.5.1} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.5.1.jar) 
    UCHIJAAAAAAAAA  SolarExpansion{1.6a} [Solar Expansion](SolarExpansion-Basic-1.6a.jar) 
    UCHIJAAAAAAAAA  SolarFlux{1.7.10-0.8b} [Solar Flux](SolarFlux-1.7.10-0.8b.jar) 
    UCHIJAAAAAAAAA  SuperMultiDrills{1.1.1} [Super Multi-Drills](SuperMultiDrills-1.7.10-1.1.1-18.jar) 
    UCHIJAAAAAAAAA  ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJAAAAAAAAA  ThermalSmeltery{1.7.10-1.2.1} [Thermal Smeltery](ThermalSmeltery-1.7.10-1.2.1.jar) 
    UCHIJAAAAAAAAA  Torcherino{2.2s} [Torcherino](Torcherino-1.7.10-2.2s.jar) 
    UCHIJAAAAAAAAA  VeinMiner{0.21.2} [Vein Miner](VeinMiner-1.7.10_0.21.2.43.jar) 
    UCHIJAAAAAAAAA  VeinMinerModSupport{0.21.2} [Mod Support](VeinMiner-1.7.10_0.21.2.43.jar) 
    UCHIJAAAAAAAAA  WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCHIJAAAAAAAAA  McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAAAAAAA  ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4101' Renderer: 'Intel(R) HD Graphics'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    RedstoneArsenal: -[1.7.10]1.1.1-89
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.1.0-161
    EnderIO: Found the following problem(s) with your installation: "Optifine is installed. This is NOT supported." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 9.17.10.4101, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by ghost** [comment]
It is?

**Comment by lumien231** [comment]
Increase your java heap space, if you don't know how to do it ask the people that made your launcher.

**Comment by ghost** [comment]
okay
