### ISSUE TITLE
Chat Detector

### ISSUE THREAD

**Issue by tyler489** [lumien231/Random-Things#300]
using the Global Chat Detector with the setting to "intercept" the chat msg and remove it doesnt seem to work the Regular Chat Detector Works Fine

**Comment by lumien231** [comment]
The Global Chat Detector can only "intercept" messages from a player it has an identity card for. Does yours have one?

**Comment by tyler489** [comment]
My mistake. Also the jei page on it is  missing lang. Its something like randomthings.global.chatdetectot.disc
