### ISSUE TITLE
EnderIO RF version

### ISSUE THREAD

**Issue by ranenvious** [lumien231/Random-Things#303]
When I attempt to load this mod along with enderIO it causes crashes while initializing the game, I checked the crash logs and it said its because this mod is loading an outdated RF version, is this a known bug, is it planned to be fixed, is there a fix.I ask these questions because I read all this mod adds and its perfect for something I really want to do, however enderIO is also a must have so I'm really hoping this is just a bug and there is a fix.

**Comment by lumien231** [comment]
What RT Version are you talking about? Random Things hasn't been shipping with the RF Api for ages.
