### ISSUE TITLE
Bean stew should probably be a shapeless recipe

### ISSUE THREAD

**Issue by TheDeviantCrafter** [lumien231/Random-Things#304]
This would keep it consistent with the other stew/soup recipes in vanilla.

**Comment by lumien231** [comment]
But Beetroot soup which is comparable in the recipe isn't shapeless ^^.

**Comment by TheDeviantCrafter** [comment]
I don't think Mojang thought beetroots through. Most players tend to ignore their existence.

**Comment by lumien231** [comment]
Well Rabbit Stew also isn't shapeless so i think i'm consistent with vanilla.
