### ISSUE TITLE
Fertilized Soil isn't recognised by Ancient Warfare 2 as useable (1.12.2)

### ISSUE THREAD

**Issue by Thessil** [lumien231/Random-Things#309]
The Fertilized Soil block isn't being recognized as soil by either Villagers, or modded NPC's from the Ancient Warfare mod. They do not use it to grow plants, is this intentional or a bug?

**Comment by lumien231** [comment]
The check Villagers use for farmland is hardcoded to vanilla farmland so without hackery i don't think i can do much about it.
