### ISSUE TITLE
Spectre Key Bug?

### ISSUE THREAD

**Issue by Azedamem** [lumien231/Random-Things#31]
Hey guys I feel as if this will be a rookie mistake but, I'm playing Random Things 2.2.4 for 1.7.10 and I was wondering why there is an OP Spectre Key but not a normal Spectre Key? I want to get to my Spectre dimension but I don't know how to with the OP Spectre Key. Thanks!

**Comment by lumien231** [comment]
Are you sure it's not disabled in the config file?
