### ISSUE TITLE
getStrongPower() Server Lag

### ISSUE THREAD

**Issue by brad18** [lumien231/Random-Things#311]
Our server has been lagging for a few weeks now and earlier today we decided to run warmroast. The server performance starts out fine after a restart but starts to decline after about 3-4 hours and gradually falls to <10tps after a couple more hours. 

I have attached a few warmroast screenshots below which show that a lot of the entities putting the most load on the server appear to be having some problems with checking redstone power. I noticed that your mod shows at the base of the tree just prior to the java array, so I thought it would be useful to see what you think might be causing this.

![1](https://user-images.githubusercontent.com/13242883/40684155-8d7e8ea8-6388-11e8-80ce-2c34cb847084.png)
![2](https://user-images.githubusercontent.com/13242883/40684157-8d9c7f6c-6388-11e8-9e01-1ed46cc01e01.png)
![3](https://user-images.githubusercontent.com/13242883/40684158-8dba8a98-6388-11e8-8be3-90650d3f7a76.png)
![4](https://user-images.githubusercontent.com/13242883/40684159-8ddaa832-6388-11e8-870a-4b60d0e0b1e5.png)

Thanks for your time.

**Comment by lumien231** [comment]
Could you maybe check whether the amount of TileEntityRedstoneInterface instances grows over time or stays mostly constant?

**Comment by brad18** [comment]
Can you recommend a way/mod that can track this please?

**Comment by lumien231** [comment]
I don't know of any mod that can do it but [VisualVM](https://visualvm.github.io/) is similiar to Warmroast and has that capability.

**Comment by superfluke** [comment]
I think this is what you're looking for, but let me know if you need something else.

This is the dump from the server just after a restart:
![image](https://user-images.githubusercontent.com/20022336/40866681-0ed8d9c2-65cd-11e8-9d44-003558659ddf.png)

And here's the dump from just before that reset (after the server had been running for 4.5 hours):
![image](https://user-images.githubusercontent.com/20022336/40866696-2ef6243a-65cd-11e8-8c98-b87c9daf7a9f.png)

**Comment by budgej** [comment]
I think this issue still persists.  I haven't looked for this function in other areas, but it is definitely slowing down Refined Storage controllers.  In this image, getStrongPower() is taking 4.5 ms of the controller's 11 ms overall time.  There is also an example in onPostWorldTick (1.5 ms of 3.5 ms is spent on getStrongPower).  I've included two sampler reports, one with RandomThings and one without.
[With](http://www.mediafire.com/file/8ttq566c5d71xm1/WithRandomThings.nps/file)
[Without](http://www.mediafire.com/file/yhfxq49pgylpywp/WithoutRandomThings.nps/file)
![profiler image](https://user-images.githubusercontent.com/3517766/52372617-9fd26380-2a26-11e9-904d-4f5ac2002a4e.png)

**Comment by lumien231** [comment]
> I think this issue still persists. I haven't looked for this function in other areas, but it is definitely slowing down Refined Storage controllers. In this image, getStrongPower() is taking 4.5 ms of the controller's 11 ms overall time. There is also an example in onPostWorldTick (1.5 ms of 3.5 ms is spent on getStrongPower). I've included two sampler reports, one with RandomThings and one without.
> [With](http://www.mediafire.com/file/8ttq566c5d71xm1/WithRandomThings.nps/file)
> [Without](http://www.mediafire.com/file/yhfxq49pgylpywp/WithoutRandomThings.nps/file)
> ![profiler image](https://user-images.githubusercontent.com/3517766/52372617-9fd26380-2a26-11e9-904d-4f5ac2002a4e.png)

Could you create a seperate issue for this?
