### ISSUE TITLE
Diaphanous Blocks Freeze/Crash

### ISSUE THREAD

**Issue by Shahelion** [lumien231/Random-Things#314]
My game is still frozen at the moment, but if it crashes I'll update with the crash log. I'm leaving it alone for now to see what happens.

I made some Diaphanous Blocks, no problem. I textured them with Botania's Livingrock Bricks, fine. I placed them in the crafting grid planning on inverting them, but changed my mind. I took the blocks out of the crafting grid, but before I could place them back in my inventory, the game froze. I could still see the crafting result even though the grid was empty.

EDIT: I just noticed this in the console: https://hastebin.com/adixunenav.lua

I killed the game, it was stuck for too long. Nothing was happening. Loading it back up, hopefully the world is fine.

EDIT 2: Loaded back up just fine. Haven't tried to reproduce it yet.

**Comment by lumien231** [comment]
Maybe it's only broken for me but the hastebin is empty for me?

**Comment by Shahelion** [comment]
God dammit...hold on, let me see if I can recover it.

**Comment by Shahelion** [comment]
Try this: https://gist.github.com/Zsashas/a647817b1e236acaf7cab8105693bffb
