### ISSUE TITLE
Diaphanous Null-pointer

### ISSUE THREAD

**Issue by Darkmega18** [lumien231/Random-Things#316]
random things 4.1.8
forge 2705
Playing on server, crashed the client after a short freeze when I tried to place one of them down to check out the sight distance on them. I do have optifine, which could causing some tossing up with them perhaps? I don't know, but heres the crash. it didn't take the server with it but I appear to be unable to get back on cause the block must still exist or something and is causing me to instant boom.

[crash-2018-06-28_21.34.46-client.txt](https://github.com/lumien231/Random-Things/files/2145116/crash-2018-06-28_21.34.46-client.txt)

**Comment by lumien231** [comment]
Can you reproduce this?

**Comment by Darkmega18** [comment]
I'm trying it now without optifine to see if I can access my server to see if maybe opti's doin something funky on the render making client blow up and not the server cause it don't care bout rendering. cause i just got kicked out of it again instant with the same crash when I rejoined. back in a few mins when my game loads. :V

**Comment by Darkmega18** [comment]
and I'm gone again. optifine having been taken out as a test.

[crash-2018-06-28_21.57.22-client.txt](https://github.com/lumien231/Random-Things/files/2145149/crash-2018-06-28_21.57.22-client.txt)

same crash about tessellation. well, looks like my building plans are on hold for now then. :V and probably same for others too if I had to figure if my friend goes back on over night...

**Comment by lumien231** [comment]
What Block did you make them look like?

**Comment by Darkmega18** [comment]
it was just pure default stone, same as they came out. 

placed one in the world a short distance ahead of me to check out the whole fading in and out thing to see the distance on it to plan a build project using them. game froze then blew up the moment it was placed on the ground. Hwyla was displaying the block on the screen for a moment before hand.

**Comment by lumien231** [comment]
Just pushed v. 4.1.9 to curseforge. If that doesn't fix it could you check whether this still happens with only RT installed?

**Comment by Darkmega18** [comment]
will take a bit, but I'll try to. I can probably just load a 1.12.2 vanilla in technic then throw forge onto it and try them quickly.

**Comment by Darkmega18** [comment]
Er. no 4.1.9 on curse yet. did something go wrong? I finished watching a video first. :V

**Comment by lumien231** [comment]
Nah just takes awhile for them to approve it.

**Comment by Darkmega18** [comment]
ah, yeah, moments later, thats what I figured it'd be, so watched another video. lol.

**Comment by Darkmega18** [comment]
shit. I just realized. when I had first taken out optifine I actually hit update on my pack and so it actually updated and put optifine back in.

with optifine properly disabled the block worked fine and didn't crash. :V however I now have a considerably larger amount of lag in an area that usually plays alright. so thats awkward. Would this fix do anything potentially for making them workable with optifine? or is optifine just one of those "well, you're shit out of luck" things with you aswell? :<

**Comment by Darkmega18** [comment]
4.1.9 doesn't help with the crash on placing diaphanous blocks.

However I have confirmed that it's optifine causing the issue as it works when I actually remove optifine and test it and not accidentally update and have it turned back on. :V 
fast render is on, cause I know a lot of things get salty when thats not on. and having fast off bugs with a few other things in my pack.

**Comment by lumien231** [comment]
Ok i know why this happens, will try to fix it. If i can't i'll just stop them from rendering with Optifine installed.

**Comment by Darkmega18** [comment]
Alright, good luck, and thanks.
