### ISSUE TITLE
Spectre lens only works on one beacon

### ISSUE THREAD

**Issue by JillSwift** [lumien231/Random-Things#318]
I have two beacons, one providing haste 2 and the other strength 2.

Whichever beacon I put a Spectre Lens on _last_ works everywhere in the overworld, the other only within the usual 40 meter limit.

It does this whether the pyramids are [separate](https://d1u5p3l4wpay3k.cloudfront.net/minecraft_gamepedia/0/0b/Beacon_Pyramid_Arangements_12w32a.png) or [combined](https://d1u5p3l4wpay3k.cloudfront.net/minecraft_gamepedia/2/29/Efficient_beacon.png).

p.s. These spectre lenses and the spectre energy coils & injector are fantastic additions. Thanks for them!

**Comment by lumien231** [comment]
It's intentional that you can only use 1 Spectre Lens at the same time, gonna add it to the wiki page.

**Comment by JillSwift** [comment]
Awww. Ookies Dokies.
