### ISSUE TITLE
Ender Letter causing crashes/solution

### ISSUE THREAD

**Issue by Tearlow** [lumien231/Random-Things#32]
Whenever someone creates a letter they instantly crash when the gui opens up. Once restarting the client it has appended the missing NBT data and can be used. This is due to missing NBT data and can be fixed by adding compound: "Inventory" and list: "Items".

Ie. {Inventory:{Items:[]}}

Hopefully this makes some sense and should be a quick fix :)

**Comment by lumien231** [comment]
Yeah it probably would be. But the 1.7.10 version doesn't get anymore updates :/. Sorry. (And it's fixed in 1.8 already).
