### ISSUE TITLE
Operator version of the Chat Detector

### ISSUE THREAD

**Issue by Entoarox** [lumien231/Random-Things#321]
I would like it if you could add a version of the Chat Detector that works like a global chat detector, but is able to consume the chat without needing identity cards.

For security, similar requirements as with Command Blocks could be imposed on this version of the block (No recipe, must be spawned in, only OP's in creative can open the interface, etc.)

**Comment by lumien231** [comment]
Made it a command. Running /rt op <x> <y> <z>, will "toggle" a global chat detector to no longer need id cards.

**Comment by Entoarox** [comment]
Thank you, I will personally enjoy taking advantage of this functionality greatly! :)
