### ISSUE TITLE
Crashed while using Summoning Pendulum

### ISSUE THREAD

**Issue by CritFlaw** [lumien231/Random-Things#323]
Forge version:  2738
Optifine: U-D1
Minecraft version: 1.12.2
Random Things Version: 4.1.9

Crash Log: https://hastebin.com/awaqabonuh.coffeescript

What happens? Either when holding, placing, or picking up entities, the client crashes.

**Comment by CritFlaw** [comment]
Just happened again, it's when left clicking the summoning pendulum from the inventory screen, with at least one entity inside, while the item is in the hotbar.

**Comment by lumien231** [comment]
Not 100% sure whether this fixes this because i can't reproduce it but it should.
