### ISSUE TITLE
Crash to desktop seeming tied to Extraction Plate

### ISSUE THREAD

**Issue by CaithSidhe** [lumien231/Random-Things#326]
[crash-2018-07-30_00.37.11-client.txt](https://github.com/lumien231/Random-Things/files/2239704/crash-2018-07-30_00.37.11-client.txt)

The crash is quite repeatable on the server I am playing on and happens when looking up the uses of several blocks. Looking up the use of Cobblestone and the Extraction plate has triggered the crash so far from my experience but others have said that other blocks and machines trigger the same crash.

**Comment by walker-dev** [comment]
[crash-2018-08-03_23.35.39-client.txt](https://github.com/lumien231/Random-Things/files/2258881/crash-2018-08-03_23.35.39-client.txt)

similar crash here.
