### ISSUE TITLE
enderio fused quarts JEI lookup crash

### ISSUE THREAD

**Issue by redgoblin88** [lumien231/Random-Things#328]
i am playing on enigmatica2 expert and a certain recipe uses fused quarts, but upon me trying to craft it no valid recipe came up so i thought "this doesnt work? what is the recipe then" so i decided to see the uses for the enderio fused quartz glass but uopn searching with JEI (U on the item, not the side menu) i crashed. in the report it says something about it being a random things issue with a blockstate problem?

heres the crashlog:
https://pastebin.com/raytQQfi

mod versions are as follow

random things: 4.2.0
JEI: 4.11.0.206
Enderio: 5.0.30
Forge: 14.23.4.2739
modpack version: Enigmatica 2 Expert - 1.34

**Comment by lumien231** [comment]
Same thing as #326
