### ISSUE TITLE
Add configuration options to control mod features

### ISSUE THREAD

**Issue by rintaun** [lumien231/Random-Things#33]
It would be nice to have the ability to disable particular features of the mod (an option which many other mods provide) so that the mod can be tailored to fit a particular environment. For example, the ability to disable worlgen:

```
worldgen {
    B:GeneratePlants=true
    B:GenerateCores=false
}
```

The more features covered, the better!

**Comment by lumien231** [comment]
Yeah, in the 1.7.10 Version i had a config Option for basically everything... I was just too lazy to implement them in 1.8. Will do that soon!

**Comment by CNakai** [comment]
Do you have an estimated time to completion for being able to toggle arbitrary features? I'd love to run this on my server, but some of the items would break how we play.

**Comment by lumien231** [comment]
I won't add config options for all blocks / items, just use "config" mods to remove the recipe for them.

**Comment by CNakai** [comment]
Interesting. Do you have a config mod you recommend?

**Comment by lumien231** [comment]
Not really, never used them myself.
