### ISSUE TITLE
JEI/enderIO problem?

### ISSUE THREAD

**Issue by Iashar** [lumien231/Random-Things#332]
#### Issue Description:
Crashed when right clicking a quartz slab for more recipes in JEI.

#### What happens:
Game locked up, shut down internal server, then proceeded to close to desktop.

#### What you expected to happen:
Expected to get more options from JEI for what I could do with Quartz slabs.

#### Steps to reproduce:
I also have 'EnderIO' mod installed.
Will be reporting this to them as well.
1.open recipes for Quartz blocks
2.Find where it tells you how to make quartz slabs
3.right click quartz slab
...crash
#### Affected Versions (Do *not* use "latest"):

- RandomThings-MC1.12.2-3.9.3.324-universal.jar
- Minecraft: 1.12.2
- Forge: 14.23.4.2747
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

https://pastebin.com/0NNPLskU

**Comment by lumien231** [comment]
Don't create an issue before making sure it also happens with the latest version of the mod please.
Maybe even check recently closed issues.

This is a duplicate of 
#331 
#329 
#328 
#326

**Comment by Iashar** [comment]
Sorry, didn't know there was an update, thanks for your prompt response!
(also new to using github for crash reporting, will be sure to keep that advice in mind next time round.)
