### ISSUE TITLE
1.7.10 bloodstone not working

### ISSUE THREAD

**Issue by TheBalanceKeeper** [lumien231/Random-Things#340]
I got a bloodstone in resonant rise and got it to full charge but it wont give me regen.

**Comment by lumien231** [comment]
Sorry but i don't support the 1.7.10 version anymore.

**Comment by Shahelion** [comment]
I know this is old, but this is the only place I figured I could get an answer. In 1.7.10, how is the regen applied? Via a potion effect or invisibly? If it's supposed to be via potion effect, then it is indeed broken.

**Comment by TheBalanceKeeper** [comment]
It actually doesn't show any proof of regen until you get damaged. You get
healed quickly.
