### ISSUE TITLE
Spectre Sword Not Appearing in JEI, Uncraftable

### ISSUE THREAD

**Issue by DrCryllus** [lumien231/Random-Things#346]
What it says on the tin. Playing the stoneblock modpack, which has more than enough mods for it to be something else's fault. Still,  decided to make a note here that there is an issue.
Edit: After creating a new minecraft instance with only JEI and Randomthings, I found that the Spectre Key and Spectre Anchor are also missing from JEI in stoneblock. I am happy to debug this myself, I just need a little help with finding the tools to fix it.
Edit2: After Poking around for a while I found the swords ID, and was able to able to summon it via console commands. It still did not appear in JEI, and displayed no crafting recipe when clicked on.

**Comment by lumien231** [comment]
Are you sure the Modpack Author didn't just remove it from JEI? If it only happens in the Stoneblock Modpack i doubt it has anything to do with Random Things.

**Comment by Lost-Ninja** [comment]
It's disabled by pack author along with the key and some other RT things IIRC.

**Comment by DrCryllus** [comment]
Huh. Weird. I'll go pester them about it then. Thanks!
