### ISSUE TITLE
crash with custom workbench in forge 1.8

### ISSUE THREAD

**Issue by SDUBZ** [lumien231/Random-Things#35]
havent even got a custom workbench in my base and still causes crashes fix it please http://pastebin.com/crKkWG6j

**Comment by lumien231** [comment]
So what block do you have at 765,73,1227 ?

**Comment by SDUBZ** [comment]
it was just a vanilla crafting table wierd O_O

**Comment by lumien231** [comment]
Sooo removing it fixed this?

**Comment by SDUBZ** [comment]
yes it fixed by removing the crafting table
