### ISSUE TITLE
Luminous Gray Stained Bricks don't emit any light levels (1.12.2 Version 4.2.1.2)

### ISSUE THREAD

**Issue by SpeedSlider** [lumien231/Random-Things#353]
I created some luminous gray stained bricks thinking they would emit some light levels since they use glowing mushrooms and glowstone dust in the recipe. They don't look different then gray stained bricks and they don't emit any light levels.

**Comment by lumien231** [comment]
Did you look at the [Wiki Entry](https://lumien.net/rtwiki/blocks/stained-bricks/)? If they don't look like that i'm guessing you have Optifine installed. The Glowing Effect doesn't work if Optifine is installed.
