### ISSUE TITLE
Time in a Bottle "lag"

### ISSUE THREAD

**Issue by Yamza** [lumien231/Random-Things#355]
Having several Time in a Bottle causes crippling lag. I did go a bit excessive on this for verification but if this can be done by a single player it seems like a bit of an issue. Even worse that you can't tell what's causing it by profiling.

Profile of what seems to be the event related to this: https://sparkprofiler.github.io/?qdTgjpmBrH
The line in question: https://i.imgur.com/f02uVxt.png
Inventory: https://i.imgur.com/b1Hbj28.png
TPS with the Time in a Bottle: https://i.imgur.com/aCCur2A.png
TPS after removing them all: https://i.imgur.com/IjWGwTw.png

Additional from another server: https://minecraft.curseforge.com/projects/random-things?comment=436

## Mod Versions
Modpack: ATM3 - Remix 1.0.0
Minecraft: 1.12.2
Forge: 14.23.5.2768

Random Things: 4.2.2

**Comment by lumien231** [comment]
Already fixed in 75a493848d1d29a94eec99586ebfbb1b75836c55
