### ISSUE TITLE
Suggestion with Advanced Redstone Repeater.

### ISSUE THREAD

**Issue by Glittersword** [lumien231/Random-Things#358]
You really need a better interface than the + and - signs.  That is a lot of clicking to get into the 5000 plus range.  I am trying to automate the Thermalillies from Botania.  Releasing enough lava for 7  Lillys. then closing a piston over the lava drop area until the plants cooldown has expired. Rinse and repeat.

This suggestion would also be appropriate for the Advanced Redstone Torch.

**Comment by lumien231** [comment]
Not sure whether you knew but shift already increased the amount by which it changed.

With this it's:

Shift: 10
Ctrl: 100
Both: 1000

The Advanced Redstone Torch only goes from 0-15 and already has the shift functionality so i don't think more is necessary there.
