### ISSUE TITLE
Config option to disable Magnetic?

### ISSUE THREAD

**Issue by Bluberry-Kat** [lumien231/Random-Things#361]
You've mentioned before that you only add configs for things a player can't just disable by removing the recipe for.

Is there any chance there could be a config to remove the Magnetic enchant? It conflicts with a feature from another mod I have and I'd like to not have two of the same thing.
(If not, is there an external method to remove it from the enchantment table? Thank you.)

**Comment by geqo** [comment]
In my case Magnetic enchant doesn't work and i want disable it to.
