### ISSUE TITLE
Position filter does not work with biome radar

### ISSUE THREAD

**Issue by CritFlaw** [lumien231/Random-Things#362]
Forge 2780
Mod version 2-4.2.4

When right clicking the biome radar (after it's found the biome) with a position filter, it highlights it, and copies the machine's position in the filter, as opposed to wherever the biome was found.

**Comment by lumien231** [comment]
[You can now get a position filter of the position the biome was found at by right clicking the biome radar with a piece of paper.](https://lumien.net/rtwiki/blocks/biome-radar/)
