### ISSUE TITLE
[1.12.2] Item Filter Duplication 

### ISSUE THREAD

**Issue by Cazadorsniper** [lumien231/Random-Things#363]
If you shift-click item filters fast enough into the item collectors the item filters will duplicate.

Could be because of mouse tweaks but unsure.

**Comment by roulito** [comment]
If we kill the spectre illuminator entities with a /kill@e[type=spectreilluminator] command, the light update doesnt do that and we find it with a still bright chunk.

**Comment by TheDeviantCrafter** [comment]
I wasn't able to replicate this issue. I tried it by hand and with an autoclicker. I do not have Mouse Tweaks installed, but I do have Inventory Tweaks and item scroller.

**Comment by Cazadorsniper** [comment]
It was something reported to me while in PO3 testing.
