### ISSUE TITLE
Spectre Dimension and Digital Miners

### ISSUE THREAD

**Issue by TerdyTheTerd** [lumien231/Random-Things#37]
So the problem is this, players can place digital miners down from Mekanism, and then set the radius to 32, and set it to inverse from say dirt, so it will mine anything but dirt. It won't mine the spectre blocks, which is good, but it will mine blocks that are inside other players spectre cubes, essentially letting anyone grief the cube right next to theirs. Not sure if you could add a config to let admins change the distance that the spectres are from each other, or add in something that doesn't let Digital miners be placed at all.

**Comment by lumien231** [comment]
The 1.7.10 version does not get updates anymore i'm afraid. If i add the spectre dimension in 1.8 i will think up a solution.
