### ISSUE TITLE
request - Time in Bottle offline charging

### ISSUE THREAD

**Issue by kreezxil** [lumien231/Random-Things#373]
Could it be possible to allow the Time in a Bottle to be configurable as to allow offline charging and have that enabled by default. This would eliminate the need for players to stay logged on to server while they are at work to charge their bottles and thus allow slots to be freed up for other players to join a server.

**Comment by lumien231** [comment]
Will probably go the opposite route and prevent charging it while afk. Sorry ^^.

**Comment by kreezxil** [comment]
how about adding a config to it that allows a pack developer to determine
it works with afk, offline, or active only.

**Comment by kreezxil** [comment]
I realize why you are going the other direction but it won't help because a player in motion is player not afk. 

There are any number of afk machines a player can make. The most common one is swirling water, the player rides a boat that goes round and round. Another is track that pushes the player on a minecart round and round. So a server will still have players logged in, not playing, charging bottles while being in  an afk machine. 

These easiest solution is to allow offline charging.

I was gonna show you some pictures but this link will do just fine. https://www.google.com/search?tbm=isch&source=hp&biw=1584&bih=751&ei=CrdJXP7qFMq4sQWC8aSwAg&q=minecraft+afk+machine&oq=meatlover&gs_l=img.3..0i10j0j0i10j0l2j0i10l5.1527.2635..2677...0.0..0.120.653.5j2......1....1..gws-wiz-img.....0..35i39.jRBjYE0iv_Y

**Comment by lumien231** [comment]
Well i will not base it on movement but user input. I'll probably add a config option, though the default will be no afk / offline charging.
