### ISSUE TITLE
Golden chicken balancing

### ISSUE THREAD

**Issue by praecipitator** [lumien231/Random-Things#375]
IMO, the golden chicken is absolutely overpowered. Get one of them, put it onto a hopper, and gold is about as scarce as cobblestone.
Yes I know it can be disabled, but what's the point of even having it in the mod then?

Some ideas how it could be balanced:
- Make it drop nuggets instead of gold bars. That would make it at least a little better, but probably not much...
- Give it a finite lifespan. Effectively this would mean, the chicken is only good for a certain amount of gold ingots.
- Make it require food. It could be gold ore, basically turning the chicken into an ore refinery. One block of gold ore allows the chicken to lay up to 5 gold ingots. This would also make having more than one chicken useful: feed each one a block and have them lay gold in parallel, instead of waiting for the single chicken to finish,
Otherwise, I think even seeds would be enough as chicken food. Just the very fact that player interaction is necessary would prevent automatic gold farming.

**Comment by lumien231** [comment]
Good Idea!
