### ISSUE TITLE
Request: Configurable recharge speed for the Time in a Bottle

### ISSUE THREAD

**Issue by TheDeviantCrafter** [lumien231/Random-Things#378]
The pack I'm working on has no tick acceleration blocks. Tick acceleration isn't something I believe should be automated, but there are cases where I want people to be able to accelerate things manually. Time gating just isn't fun, but I want people to accelerate their farms to insanity.

The time in a bottle is the perfect solution to this problem. It can't be automated even with autonomous users, because it needs to be in your inventory. In playtesting I found it too slow, though.

I'd like to request a configurable multiplier that controls how fast the time accumulates.

**Comment by lumien231** [comment]
Already added that in this commit, will be in the next version.
https://github.com/lumien231/Random-Things/commit/a92e910cb8e3b0471578420ad22a6010d22d950e
