### ISSUE TITLE
getStrongPower() high tick time

### ISSUE THREAD

**Issue by budgej** [lumien231/Random-Things#383]
Reposted per request.

https://github.com/lumien231/Random-Things/issues/311

I think this issue still persists.  I haven't looked for this function in other areas, but it is definitely slowing down Refined Storage controllers.  In this image, getStrongPower() is taking 4.5 ms of the controller's 11 ms overall time.  There is also an example in onPostWorldTick (1.5 ms of 3.5 ms is spent on getStrongPower).  I've included two sampler reports, one with RandomThings and one without.
[With](http://www.mediafire.com/file/8ttq566c5d71xm1/WithRandomThings.nps/file)
[Without](http://www.mediafire.com/file/yhfxq49pgylpywp/WithoutRandomThings.nps/file)
![profiler image](https://user-images.githubusercontent.com/3517766/52372617-9fd26380-2a26-11e9-904d-4f5ac2002a4e.png)

**Comment by lumien231** [comment]
That _should_ fix it, if it still happens in the next version create another issue.

**Comment by budgej** [comment]
It is down to 14.36% of the controller tick time now, from 38.16%.  Much improved.

**Comment by lumien231** [comment]
Did you build RT yourself? There isn't a released version with this in it yet ^^.

**Comment by budgej** [comment]
No, I used 4.2.6.  Interesting...  I will report back when the next version is available.
