### ISSUE TITLE
[Suggestion]Config to completely disable features separately

### ISSUE THREAD

**Issue by Blue-Beaker** [lumien231/Random-Things#385]
Quark and Cyclic have configs that you can turn every seperate feature on and off. But there is no normal way to completely disable a feature in this mod. Using crafttweaker to remove the recipe only prevents the item to be crafted, not to be loaded. This makes every disabled feature still uses memory and still show up in CreativeTab and JEI.
Please add config to disable every single feature,not just disabling the way to get it.

**Comment by lumien231** [comment]
I doubt the Block / Item instances use much memory. I believe Crafttweaker has a function that removes stuff from JEI **and** all recipes for it. 

I only add config options for features you can't just remove the recipe for.
