### ISSUE TITLE
Spectre dimension not working properly in multiplayer world 

### ISSUE THREAD

**Issue by chickenchad** [lumien231/Random-Things#388]
Ive been trying to use the spectre key on my friends modded server, however, when I enter the spectre world i get locked into a 2x2 space, with the usual room made of spectre blocks missing completely. Attempting to leave the space will result in a teleport back and a slowness debuff. My friend is able to move freely as an OP. Is there a way to get rid of this restriction? (version 1.7.10)

**Comment by lumien231** [comment]
Sorry but the 1.7.10 version isn't supported anymore.
