### ISSUE TITLE
Cannot launch FTB infinity with the mod 

### ISSUE THREAD

**Issue by SamuelMontminy** [lumien231/Random-Things#39]
FTB Infinity crashes when I try to launch the game with RandomThings-2.2.4 (for 1.7.10) installed. I am using Infinity Evolved v2.2.2 and the Launcher: v1.4.3. I have absolutely no idea what is causing the crash so I post this here for anyone that has somewhat of an idea. I also managed to take a screenshot of the ftb console just before it crashes.
![capture d ecran 26](https://cloud.githubusercontent.com/assets/16582857/12155169/222442e6-b49a-11e5-8574-9f5c0f7183c2.png)

Here is the list of mods I have installed:

AOBD-2.8.4
bdlib-1.9.2.104-mc1.7.10
BiblioCraft[v1.11.4][MC1.7.10]
BiblioWoods[BiomesOPlenty][v1.9]
BiblioWoods[Natura][v1.5]
BiomesOPlenty-1.7.10-2.1.0.1067-universal
BrandonsCore-1.0.0.10-bugfix
Carpenter's Blocks v3.3.7 - MC 1.7.10
Chisel-2.9.3.9
CodeChickenCore-1.7.10-1.0.7.47-universal
CoFHCore-[1.7.10]3.0.3-303
CoFHLib-[1.7.10]1.0.3-175
compactmachines-1.7.10-1.18
CustomMainMenu-MC1.7.10-1.9.2
denseores-1.6.2
EnderCore-1.7.10-0.2.0.31_beta
EnderIO-1.7.10-2.3.0.421_beta
EnderStorage-1.7.10-1.4.7.37-universal
EnderTech-1.7.10-0.3.2.405
EnderZoo-1.7.10-1.0.15.32
EnhancedPortals_1.7.10-universal-3.0.12
ExtraTiC-1.7.10-1.4.5
extrautilities-1.2.12
fastcraft-1.21
FastLeafDecay-1.7.10-1.3
FTBLib-1.7.10-1.0.11.3
FTBTweaks-1.0.0
FTBUtilities-1.7.10-1.0.11.3
funky-locomotion-1.7.10-beta-7
Guide-API-1.7.10-1.0.1-20
Headcrumbs-1.6.2
iChunUtil-4.2.2
INpureCore-[1.7.10]1.0.0B9-62
InventoryTweaks-1.59-dev-152
ironchest-1.7.10-6.0.62.742-universal
Jabba-1.2.1a_1.7.10
journeymap-1.7.10-5.1.3b1-unlimited
Mantle-1.7.10-0.3.2b
mcjtylib-1.8.0
MineFactoryReloaded-[1.7.10]2.8.0-104
MineTweaker3-1.7.10-3.0.10B
More-Enchantments-Mod-1.7.10
natura-1.7.10-2.2.0.1
neiaddons-1.12.11.36-mc1.7.10
NetherOres-[1.7.10]2.3.0-12
NotEnoughItems-1.7.10-1.0.5.118-universal
NotEnoughResources-1.7.10-0.1.0.106
OpenBlocks-1.7.10-1.4.4
OpenModsLib-1.7.10-0.8
RandomThings-2.2.4
RedstoneArsenal-[1.7.10]1.1.1-89
ResourceLoader-1.2
rftools-4.13
runicdungeons-1.1.6a
SimplyJetpacks-MC1.7.10-1.5.3
SolarExpansion-Basic-1.6a
SoundFilters-0.8_for_1.7.X
Springboards-1.7.10-0.1
TConstruct-1.7.10-1.8.8
ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.0.3B1-218
ThermalFoundation-[1.7.10]1.2.0-102
TiCTooltips-mc1.7.10-1.2.5
TMechworks-1.7.10-0.2.14.100
Translocator-1.7.10-1.1.2.15-universal
Waila-1.5.10_1.7.10
WailaHarvestability-mc1.7.10-1.1.5
Wawla-1.3.3-1.7.10
WR-CBE-1.7.10-1.4.1.9-universal

**Comment by lumien231** [comment]
Remove Fast Leaf Decay, it's included in Random Things.

**Comment by SamuelMontminy** [comment]
Hey thanks a lot for the very quick response, and it worked!  thanks a lot :D
