### ISSUE TITLE
issue with fast leaf decay?

### ISSUE THREAD

**Issue by zymex22** [lumien231/Random-Things#391]
are randomthings mod stil doing anything to leaf decay? =) or can i use fast leaf decay now?
coundt find any new threads or config if RT still does something to leaf decay?

anyways what does Random things do to leaf decay coundt read on wiki or anywhere =)

**Comment by lumien231** [comment]
Random Things doesn't include any Fast Leaf Decay anymore so it works fine with fast leaf decay mods.
