### ISSUE TITLE
Random Things breaks JEI tabs for latest GTCE build

### ISSUE THREAD

**Issue by WarlordWossman** [lumien231/Random-Things#400]
https://hastebin.com/ikimaparab.rb

happens with Random Things 4.2.7 and GTCE 387

**Comment by Saereth** [comment]
Yeah looks like some asm you're doing with the redstonehandler is now kickin off before gtce is fully loaded so its crashing the jei plugin resulting in no JEI support for GTCE or its addons. This is unfortunately a pretty huge deal for our pack (FTB Interactions) as we deeply depend on both randomthings and GTCE. I tried to look over the code and do a PR but your asm code intimidates me :P

Plz halp @lumien231

**Comment by lumien231** [comment]
Fixed in 4.2.7.1
