### ISSUE TITLE
there really needs to be some config options to enable or disable certain features...

### ISSUE THREAD

**Issue by gravysamich** [lumien231/Random-Things#402]
this mod could use a similar system to quark where you can enable or disable certain things. as it stands, it is kind of an all or nothing deal. 

this is great if you want everything this mod has, but it really sucks if you only want to use some of these items. 

as a mod pack maker, i am stuck using craft tweaker to remove recipes if i don't want players using certain items. i have other mods that do similar things or in a better way so a lot of the items in this mod are redundant.

**Comment by lumien231** [comment]
It's easier for pack makers to remove recipes using something like Crafttweaker than for me to add config options for everything or make the mod "modular". I only add config options for features you can't just remove the recipe for.
