### ISSUE TITLE
Golden chicken bug

### ISSUE THREAD

**Issue by ToastedMarsh** [lumien231/Random-Things#406]
My golden chickens wont produce gold anymore. im using twitch launchers lapitos galacticraft version 1.12.2. How do I fix this?

**Comment by zISKo666** [comment]
Hello,

I have my own 1.12.2 mod pack but the golden chicken won't lay gold ingots.

**Comment by lumien231** [comment]
Oh yeah, still have to update the wiki article. It now triples gold ore you throw at it instead of just laying gold ingots.

**Comment by zISKo666** [comment]
Hehe, thank for the information ;)
