### ISSUE TITLE
[1.8.9] Lava Charm not working?

### ISSUE THREAD

**Issue by Darkhax** [lumien231/Random-Things#41]
The Lava Charm doesn't seem to work. When touching lava, the player will catch on fire and take damage, and the HUD will tick down. I tested this in both the surface and the nether, and in the baubles slot, the hand and the inventory, but the player still gets hurt. 

Version:3.5.7

**Comment by lumien231** [comment]
You will still get set on fire with a lava charm, it only negates the lava damage. For NO damage in lava you would also have to carry a obsidian skull.
