### ISSUE TITLE
[CTD] [Rendering] [Incompatibility] - CTD with Specter Coils and Albedo 

### ISSUE THREAD

**Issue by Lanse505** [lumien231/Random-Things#417]
Hello o7

So during testing for Resonant Rise 5, we've started running into some sporadic crashes which point towards specter coils. After talking about it a bit, @thecodedone pointed out it might be an issue between Albedo's new Lighting Capability system making the Specter Coil go into a hissy-fit.

[Here's the logs](https://gist.github.com/Lanse505/586e2cf10dc8d8d62b39741f996697d8)

**Comment by Y0ungSandwich** [comment]
We are having the same issue with:
	RandomThings-MC1.12.2-4.2.7.1.jar
https://hastebin.com/nutanovifo.sql

On our pack Mech & Magic
https://www.atlauncher.com/pack/MechMagic

**Comment by querns** [comment]
I'm having a similar crash.

https://pastebin.com/B9fD5UNP
Pack is FTB: Interactions version 1.9.0.

Some more information: the crash occurs when traveling away from my base, when chunks start to get unloaded. I crash to desktop after some offending chunk gets unloaded. If I try to reload my map, I crash again immediately with the same error. Going into the graphics options before I load my map and turning the max chunk distance to something very low, then teleporting back to my base allows everything to function again.

**Comment by A-UNDERSCORE-D** [comment]
Conforming this for FTB: Interactions. Related issue: https://github.com/FTBTeam/FTB-Interactions/issues/730

**Comment by lhw** [comment]
We can add ATM3-Remix to that list with the same rendering/lighting interaction with `p455w0rdslib.capabilities.CapabilityLightEmitter.hasCap` AllTheMods/ATM3-Remix#218
