### ISSUE TITLE
[1.8.9] Redstone Interface Isn't Working

### ISSUE THREAD

**Issue by Ratismal** [lumien231/Random-Things#42]
I can't seem to get the redstone interface to work.

![2016-01-14_09 46 18](https://cloud.githubusercontent.com/assets/1059362/12330705/aee7363e-baa3-11e5-9871-67ff34a7cb7f.png)

They don't emit a redstone signal no matter what I try, even when using the images on the wiki as a reference. Am I doing something wrong or are they just broken for 1.8.9?

I'm using version 3.5.7.

**Comment by lumien231** [comment]
Hmm works fine for me on latest forge. Do you have any other mods installed?

**Comment by Ratismal** [comment]
Nope, I only have Random Things installed.

I'm currently running on version 11.15.0.1694 of forge. I'll update to the latest version and try again.

EDIT: Works on 1697 but not 1694. Weird! Sorry.
