### ISSUE TITLE
About the Spectre lens in servers

### ISSUE THREAD

**Issue by AshuraBilly** [lumien231/Random-Things#420]
Does the spectre lens's effect only work for one player?

When the spectre lens set up on the beacon, the beacon's buff only will share to me without other players which are in the same dimension :(

**Comment by lumien231** [comment]
Yes, it only works for the player that placed it.

**Comment by AshuraBilly** [comment]
Okay, still has one more question that I know the spectre lens only can place one on the beacon as having multiple ones will make them overwrite each other. 

However, as you said that it only works for the player that placed it. So, how about I build one more new beacons and Player B put the lens on top. The new one will work for him? and mine still works for me?
