### ISSUE TITLE
Spectre Illuminator makes blocks wobble back and forth

### ISSUE THREAD

**Issue by TechnoMagi** [lumien231/Random-Things#425]
When I place the spectre Illuminator and look at it, blocks wobble back and forth, this is in the Project Ozone 3 pack. It stopped the moment I picked it up, and resumed if i placed it back down. As long as the Illuminator is within my vision field the blocks wobble

**Comment by ECrownofFire** [comment]
Caused by it not rotating the matrix back properly: https://github.com/lumien231/Random-Things/blob/1.12.2/src/main/java/lumien/randomthings/client/render/RenderSpectreIlluminator.java#L77-L90

Also happens with the time in a bottle: https://github.com/lumien231/Random-Things/blob/1.12.2/src/main/java/lumien/randomthings/client/render/RenderTimeAccelerator.java#L84-L124

Possibly affects others, but I haven't looked through them all. Should probably just use the matrix stack.

**Comment by lumien231** [comment]
I might be missing something but shouldn't rotating them in reverse be exactly "rotating back" ?

I also can't reproduce this, does this also happen with only RT installed?

**Comment by ECrownofFire** [comment]
Oh sorry, I misread that.

I think it depends on the rendering order of entities, so it doesn't always happen, and it doesn't affect every entity, which makes it a massive pain to test. I'm not sure how that order is determined, but it seems consistent if I connect, disconnect, and reconnect to the same SMP server. But if I restart the server itself, then it changes.

Also to give some more details on the "wobbling", it seems like everything wobbles *towards* the time accelerator thing, and placing more of them down makes it worse, and they wobble towards the center point of them. They also wobble more as you increase the acceleration.

**Comment by Kyzoku** [comment]
This might also be something that only affects AMD graphics card users as well, but I don't know for sure.  I play with 2 other people 1 of them uses nvidia and the other an amd like myself and the one with nvidia doesnt get the problem.

I took a video of the problem if you wanna see.
https://external-preview.redd.it/QqgaeZ40FcRM3P8A2sryMpr9g0Rolo5OWICV3Ts4JjE.png?width=960&crop=smart&format=pjpg&auto=webp&s=9fd933165ea461622a5e8533ea793db786de1e43

Original Link to Reddit Post in case the previous link doesn't work.
https://www.reddit.com/r/ModdedMC/comments/d31vw8/can_anyone_here_help_with_a_problem/

EDIT:
The effect for me can sometimes take 30+ minutes before showing its ugly head.

**Comment by cheshyrp** [comment]
This bug affects nVidia GPU's as well; not just AMD. I thought I'd fixed it by uninstalling Optifine, but no such luck. Optifine appears to exacerbate the problem, but it happens even on vanilla Minecraft + Random Things and Forge.

**Comment by VADemon** [comment]
This is not just unique to AMD cards, many comments state their assumptions as facts (reddit thread).
We all have observed this behaviour: GTX 780, RX 580, RX 5700XT. It happens as soon as Spectre Illuminator is not culled, in render view within view-distance. Looks like any custom entity is rotating around it's origin: YABBA barrels titles, mod ender chest, fluids rendered in TC's smeltery.

> I might be missing something but shouldn't rotating them in reverse **be exactly** "rotating back" ?

Finite precision numbers, decimal to binary conversion and back, rounding errors. Pick a few :) This isn't algebra.

**Comment by Ganboo** [comment]
any updates on at least a temp fix for this? cause i'd say its getting pretty hectic for me
[https://i.gyazo.com/8e9c5d962cb4eb5fc75f5b3ce03bbd6a.gif](url)

**Comment by Urahara721** [comment]
I'm also having this issue with a GTX 1070ti. Had to stop using the illuminators because it was so jarring. Is there at least a simple workaround where I could disable the animation on the illuminators or something?

**Comment by GamingReborne** [comment]
I'm having this issue in MC.Eternal which I am running on a server. There are other people on the server that do not have this issue.
My graphics card is a GTX 1080 Ti.
I've also found that the issue gets worse the longer I leave the game running. Quitting to the menu doesn't help but if I close the game and start it up again, it resets the severity of the issue.

**Comment by Cryotheus** [comment]
One of my friend's is experiencing this issue as well. I hope it can get fixed soon, it seems to be pretty annoying.
https://youtu.be/zcM6Szs0-EE

**Comment by BioPrince** [comment]
Resonant Rise 5 pre, after placing the spectre illuminator, chests and drawer item pictures and the lava in a tinkers' smeltery will not stop moving around.

**Comment by lumien231** [comment]
Fixed in 4.2.7.4
