### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot get property PropertyDirection

### ISSUE THREAD

**Issue by Frekvens1** [lumien231/Random-Things#426]
[Forge Version]: 1.12.2 - 14.23.5.2838
[Mod version]: MC1.12.2-4.2.7.2
Crash-log: [LINK](https://gist.github.com/Frekvens1/d1e5323f89b605dc01c6d242c64e5f09)

Whenever I have loaded the chunks with block '152,69,265' and then traveling away from it, the whole game crashes once it unloads. This happens to all the players on the server. This is quite troublesome as this block is infact the spawnpoint.

According to the crash-log, this block is an air block. It used to be an air block, but I've placed a bunch of stone there to see if it changed, which it didn't. There have never been any blocks on these coordinates until now.

**UPDATE**: I tried changing the spawnpoint one block above the previous one, which is still inside the stone structure. The game now crashes after a few seconds when rendering the spawn chunk. I get the same crash-log, but with the block of cause as ('152,70,265'), which means it is the spawnpoint which is causing the crash exception.

**UPDATE**: I've changed the spawnpoint further away ('499,100,499') (Server running with borders, this is the limit), and I still crash the same. However, I am still at the old location. Which means I haven't even loaded that new chunk. I don't crash straight away when at other locations, including the new spawnpoint.

Am I the only confused one here?

**UPDATE**: I created a new server and everything seems to work fine. The other server used to be like this too. I first encountered it while flying over the spawn area with the 'Psi' mod. Not sure if this helps, but might be worth putting here.

**Comment by Frekvens1** [comment]
**UPDATE**: I tried changing the spawnpoint one block above the previous one, which is still inside the stone structure. The game now crashes after a few seconds when rendering the spawn chunk. I get the same crash-log, but with the block of cause as ('152,70,265'), which means it is the spawnpoint which is causing the crash exception.

**Comment by Frekvens1** [comment]
**UPDATE**: I've changed the spawnpoint further away ('499,100,499') (Server running with borders, this is the limit), and I still crash the same. However, I am still at the old location. Which means I haven't even loaded that new chunk. I don't crash straight away when at other locations, including the new spawnpoint.

Am I the only confused one here?

**Comment by Lartza** [comment]
passwordslib's fault, because for some reason a library mod contains render changes. Disable colored light and anything else in passwordslib that touches rendering

**Comment by lumien231** [comment]
Same issue as [this](https://github.com/lumien231/Random-Things/issues/417) one.
