### ISSUE TITLE
How do I fix this

### ISSUE THREAD

**Issue by GoatSushi** [lumien231/Random-Things#428]
I tried teleporting to w waypoint I had with journeymaps into the spectre dimension after the world was reset. I got teleported to a chunk so I disconnected. After that I tried joining again but I got an error 

internal exception io.netty.handler.codec.decoderexception java.lang.indexoutofboundsexception: readerIndex(51) + length(2) exceeds writerIndex(51): PooledUnsafeDirectByteBuf(ridx: 51, widx: 51, cap: 51)

**Comment by lumien231** [comment]
You could try to move your player back to the overworld with an NBTEditor

**Comment by GoatSushi** [comment]
I’m not the host
