### ISSUE TITLE
Can't see worlds generated with RandomThings in mods

### ISSUE THREAD

**Issue by benjohnsmith** [lumien231/Random-Things#43]
I put together a mod pack for private use (1.7.10) and desperately wanted to include Random Things. When I generate a world with Random Things present, the world is created in my local directory, but doesn't appear in the Minecraft game UI. Worlds that have been generated without Random Things in the pack are listed, but cannot be entered with Random Things present.

I tried this with a couple of versions of Random Things to see if that changed anything. I've pasted both sets of logs and some repro steps here:
http://pastebin.com/pb4Lm60G

Let me know if I can provide anything else that would be helpful.

**Comment by lumien231** [comment]
"java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered"

Try to change the id of the spectre dimension in the config file.

**Comment by benjohnsmith** [comment]
Thanks, that seems to have done it.
