### ISSUE TITLE
[Suggestion] Astral Sorcery Rock Crystal Divining Rod

### ISSUE THREAD

**Issue by Dragnier** [lumien231/Random-Things#436]
While you can find it using the mod itself, it's divining feature does not work underground and only works at night (per the mod's theme). A divining rod from your mod would make it much less annoying to find because you could locate them while still underground and during the day.

**Comment by lumien231** [comment]
Ehhh, the finding mechanic is kinda a part of the mod so i don't think i wanna mess with that.
