### ISSUE TITLE
Many items missing.

### ISSUE THREAD

**Issue by Yeetums** [lumien231/Random-Things#441]
I have looked in JEI AND the creative inventory, yet I cannot find about 9/10 of the mod. Only like 12 items can be found in the creative tab.

**Comment by lumien231** [comment]
> First 1.14 Version
>  
> 
> Stuff available atm:
> 
>  
> 
> Rainbow Lamp
> Platforms
> Fertilized Dirt
> Block of Sticks
>  
> 
> Similar to the other big MC Version updates i will update the mod block by block / item by item. I don't have the time or patience to do it all at once ^^. Will probably also use this chance to redo or outright remove some stuff i didn't like in the 1.12 Version. The 1.12 Version will still get bugfixes but no new stuff i add to the 1.14 version. Will make a seperate Wiki Page once the two versions actually diverge in content.
