### ISSUE TITLE
Spectre Room glitch with Compact Machines

### ISSUE THREAD

**Issue by maxiride** [lumien231/Random-Things#48]
I've opened the issue [here](https://github.com/thraaawn/CompactMachines/issues/169) to avoid a duplicate, I imagine it's better to keep the track of the issue in just one place.

Here a spoiler of it:

> The mods involved: RandomThings (in particular the Spectre Room) and Compact Machines.
> I'm opening just one issue ticket here and link it to the RandomThings mod because I'm not sure how and which one interferes with the other one.
> 
> What's happening:
> If I place a compact machine inside the spectre room, enter it with the shrinking device and then get back to the spectre room, if I use the spectre key to get out of the spectre room I am teleported inside the last compact machine I entered (with nausea effect) instead of the overworld. Using the command /exitspectre also brings me back into the compact machine with nausea effects.
> 
> How to reproduce it:
> 
> Use the spectre key to get into the spectre room (works as expected)
> Place down a compact machine and enter it with the shrinking device (works as expected)
> Get out of the compact machine using again the shrinking device (works as expected)
> Use again the spectre key to get out of the spectre dimension (not working->brings back into the compact machine with nausea effect)
> So this is an easy way to get trapped inside the spectre room, the only way out is suicide if you have a bed outside of the spectre room otherways is an OP /tp command.
> 
> There is something that interferes with the dimension travel both in compact machines and the spectre room, or compact machine overwrites some RandomThings value or viceversa.

**Comment by lumien231** [comment]
Commented on the CompactMachines issue. RT 1.7.10 isn't updated anymore so i can't fix this from my side.
