### ISSUE TITLE
Crashing when trying to view Anvil or Imbuing recipes in JEI

### ISSUE THREAD

**Issue by Veirilli** [lumien231/Random-Things#49]
The JEI recipe handlers for imbuing and anvil recipes seem to be calling a non-existant class. They call mezz/jei/util/StackUtil but I think that should be mezz/jei/util/StackHelper. 

Minecraft 1.8.9
Forge 11.15.1.1722
RT 3.6.1
JEI 2.25.7.145

[http://paste.ee/p/cXnrE](url)
[http://paste.ee/p/tjZYI](url)

**Comment by lumien231** [comment]
Well it was still there when i made these^^. Guess it got removed.
