### ISSUE TITLE
Illuminator B.S. 

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [lumien231/Random-Things#491]
So I'd like to ask with the spectral illuminator why in gods name its so inconsistent with how far it floats up to where you physically cannot make one damn efficient set up without this eyesore in your face which is arguably worse than torches because its lesser in quantity. Like how did you people think , oh something in which the placement is COMPLETELY out of the players control is somehow a good idea? 👎

**Comment by AnimeNerdDJBROS** [comment]
If you want to make it the full chunk but don't want in above the spectral illuminator for some reason, just fucking put a consistent Y=255 to it. Like really bruh.

**Comment by lumien231** [comment]
It floats up to the highest block in the chunk, put one at 255 if you want it that high.
