### ISSUE TITLE
Ender Letter Null Pointer Exception In GUI

### ISSUE THREAD

**Issue by thebrightspark** [lumien231/Random-Things#51]
Sometimes get a null pointer exception when trying to open an Ender Letter.
Crash report: http://pastebin.com/cruxwzdc
Using:
Minecraft 1.7.10
Random Things v2.2.4
Forge v10.13.4.1566
- Many other mods. Can provide a list if wanted.

**Comment by lumien231** [comment]
Known bug, but the 1.7.10 version isn't getting updates anymore.
