### ISSUE TITLE
---- Crash Report ---- (Ticking entity--Exp Orb)

### ISSUE THREAD

**Issue by PsiPanther** [lumien231/Random-Things#52]
Greetings!

As you can see, I have a **shameful** amount of mods (_and, I just downsized, deleting several!_), and I just updated a great number of them, including your **Random Things** mod; going from **_RandomThings-MC1.8-3.5.1_**, with _1.8-Forge11.14.1.1371_ to **_RandomThings-MC1.8-3.5.6_** with _1.8-Forge11.14.3.1450_.

I had created a new game/world after updating, and spent approx 3hrs in it, last night, and another 3hrs+/- in it, today. The primary focus of my time was spent building.

**::When the crash occurred::**
I had used a spawn egg to spawn a scorpion (via the mod **_DrZharks MoCreatures Mod-8.0.1_**). I shot and killed said scorpion using the **Crystal Bow** from the mod **_morebows-1.8-2.0.0a2_**. As the exp orbs bounced into existence, the game froze. I gave it a couple minutes, hoping it would fix itself, but soon gave up, and had to manually crash the game (using Task Manager). The game did not generate a crash report.

After this freeze-up occurred, I restarted Minecraft, and attempted to reload my game. Once the loading completed, the game crashed, my game, sadly, was corrupted.

[crash-2016-02-18_13.22.51-server.txt](https://github.com/lumien231/Random-Things/files/137095/crash-2016-02-18_13.22.51-server.txt)
[Game_Output-2016-02-18_13.22.51-server.txt](https://github.com/lumien231/Random-Things/files/137193/Game_Output-2016-02-18_13.22.51-server.txt)

I thank you for your time and attention to my issue, and look forward to your response.
_PsiPanther_

**Comment by lumien231** [comment]
Why would you update to a 4 months old version and then post issues about it? :/. This is fixed already.

**Comment by lumien231** [comment]
Oh i guess because you are still on 1.8. Sorry then, don't use platforms.

**Comment by PsiPanther** [comment]
Thank you for your time.
