### ISSUE TITLE
White stone proccing destroys soul bound items

### ISSUE THREAD

**Issue by plazia** [lumien231/Random-Things#54]
At first I thought this was an Ars Magica 2 bug. However it seems to be occurring with other mods that have their own "persist after death" mechanic.

Ars Magica 2 adds its own soulbound enchant and the Iron backpacks mod has an upgrade for the backpacks called Eternity. 

Whenever I kill myself in a manner such that the white-stone procs and saves me from death. . . Those items are immediately deleted from my inventory. 

So it seems the White stone is not respecting soulbound items. It does however work fine with the Enderi IO Soulbound enchant.

MC 1.7.10
RANDOMTHINGS-2.2.4

**Comment by lumien231** [comment]
I'm afraid Random Things for 1.7.10 isn't getting updates anymore so i can't / won't fix this.
