### ISSUE TITLE
Nature Cores should not spawn in Skyblock maps

### ISSUE THREAD

**Issue by Josephur** [lumien231/Random-Things#55]
Playing Garden of Glass or other skyblock mods you will notice that some tree/leaves get spawned as floating islands, I think it's safe to say if there's only sky around they shouldn't spawn, can give an unfair advantage to players in skyblock type maps.

**Comment by Josephur** [comment]
I know there's a config option now, however it's still something to maybe consider detecting automatically..

**Comment by lumien231** [comment]
Are you sure they are spawning in mid air at the moment (Really in the current version your game should crash when generating a skyblock map), they already shouldn't be able to do that.

**Comment by Josephur** [comment]
Ah you know what, this bug is present in the current version not taking in account the fix you created on my last Issue you've already fixed with your new isValidPosition function.  The maps we're playing on were created with RandomThings in place during world gen, that crashed initially.  So in short, this should no longer be an issue, my bad.  Closing.
