### ISSUE TITLE
Spawner Duplication Bug

### ISSUE THREAD

**Issue by Nagshell** [lumien231/Random-Things#56]
Spawner Relocator
You pick up spawner, then while placing it you need to very fast change the block you are looking at.
If done right you will place two spawners next to each other. 

One is a little buggy, it'll disappear if you do something with it, but you can use relocator again to move it - just charge tool while looking at air. (After moving it's fully working spawner)

**Comment by lumien231** [comment]
1.7.10 is not getting updates anymore

**Comment by Nagshell** [comment]
But I'm using 1.8

**Comment by lumien231** [comment]
Then i'm not sure what you are talking about, Random Things does not have a "Spawner Relocator"

**Comment by Nagshell** [comment]
Oh sorry, I thought that it was from Random Things, because it was so out of place in any other mod I ran. Sorry for bothering you.
