### ISSUE TITLE
Cant access spectre dimension

### ISSUE THREAD

**Issue by Shadowolfe** [lumien231/Random-Things#58]
after using the key i am teleported and all I see is a horizon and darkness and I am falling after a few seconds I am teleported back to where I was standing before I used the key. I am not sure what is interfering with the teleport to the room. Any suggestion to help solve this problem for me and everyone else on my server. THanks.

**Comment by lumien231** [comment]
I assume you are in 1.8?

**Comment by Shadowolfe** [comment]
no using minecraft 1.7.10

**Comment by lumien231** [comment]
Sorry can't help you then :(. 1.7.10 is not getting updates anymore.

**Comment by MJRLegends** [comment]
@lumien231 can you at least tell us the issue to why its happening?

**Comment by lumien231** [comment]
@MJRLegends I have no idea why it's happening :P, i was never able to reproduce it myself. If it still happens in 1.9 i'll look further into it.

**Comment by MJRLegends** [comment]
@lumien231 did you find out what the issue was?

**Comment by lumien231** [comment]
No, i didn't get any reports of it in 1.9.4 so i didn't look into it.

**Comment by MJRLegends** [comment]
From what i can see its because a cube isnt spawning so it just teleports the player back

**Comment by MJRLegends** [comment]
How are the cubes spawned? @lumien231
