### ISSUE TITLE
[1.8.9-3.6.5] Crash when joining server

### ISSUE THREAD

**Issue by Xiaminou** [lumien231/Random-Things#59]
Crash Report: http://pastebin.com/fDbCv8hK
rollback to previous version fixed the crash.
The server didn't crash, only client.

**Comment by lumien231** [comment]
Can you reproduce this / tell me how to reproduce it?

**Comment by Xiaminou** [comment]
I haven't tried to reproduce it, but looking at the crashlog I'd say try placing botania's sparks.

**Comment by lumien231** [comment]
Try 3.6.6 please

**Comment by Xiaminou** [comment]
Looks like it's fixed, thanks.
