### ISSUE TITLE
Exception in server tick loop when generation an SSP world.

### ISSUE THREAD

**Issue by kreezxil** [lumien231/Random-Things#6]
client crash report: http://paste.ee/p/gzcvQ
fml client latest: https://gist.github.com/kreezxil/eba09adb9fe3ed01c05c#file-fml-client-latest

**Comment by lumien231** [comment]
Can you reproduce that with only random things installed?

**Comment by kreezxil** [comment]
Dratz! No, I can't, I tried and it was just fine. :(

**Comment by lumien231** [comment]
Could you test which mod is causing it? :). Just remove half of your mods each run and it should be found fairly quick.

**Comment by kreezxil** [comment]
Yeah I know how to do that. I've done it countless times before, I call it binary searching. I'll get back to you soon on it, within a couple of hours. Starting now.

**Comment by kreezxil** [comment]
I can't reproduce it. Probably because i'm using b1446 of Forge now and in the crash report that was with b1439. I'd mark this as closed.

**Comment by lumien231** [comment]
kk :)
