### ISSUE TITLE
random-things-1.9-3.6.8.1 crashes dedicated forge server 1.9 build 1804 on startup while ticking an entity

### ISSUE THREAD

**Issue by kreezxil** [lumien231/Random-Things#65]
Issue: random-things-1.9-3.6.8.1 crashes dedicated forge server 1.9 build 1804 on startup while ticking an entity

crash report:
https://gist.github.com/270ba679b3b231a975c0

fml server latest:
https://gist.github.com/9b9965fecdf93a58fd61

**Comment by lumien231** [comment]
3.6.8.1 only works with one of the latest forge versions.
