### ISSUE TITLE
Ender Letters crash first time use

### ISSUE THREAD

**Issue by Ipiano** [lumien231/Random-Things#7]
It seems that the first time any given ender letter is used, it crashes the game client. However, the game can be re-opened, and then that ender letter will work, but other un-used ones will still crash on their first use.

Forge 10.13.3.1403 for Minecraft 1.7.10
RandomThings 2.2.4 (I believe that's the latest)

Btw, we're using a ton of mods
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/11/15 4:36 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.minecraft.crash.CrashReportCategory.func_85069_a(CrashReportCategory.java:145)
    at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:390)
    at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:357)
    at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
    at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.crash.CrashReportCategory.func_85069_a(CrashReportCategory.java:145)
    at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:390)
    at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:357)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Ipiano'/170164, l='MpServer', x=4785.77, y=62.62, z=-1038.91]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-248,64,256), Chunk: (at 8,4,0 in -16,16; contains blocks -256,0,256 to -241,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 42383014 game time, 43127095 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 49 total; [EntityZombie['Zombie'/171651, l='MpServer', x=4845.50, y=63.00, z=-1027.50], EntityZombie['Zombie'/644, l='MpServer', x=4792.30, y=36.00, z=-1014.70], EntitySpider['Spider'/170631, l='MpServer', x=4819.50, y=44.00, z=-1006.50], EntityZombie['Zombie'/171652, l='MpServer', x=4846.50, y=63.00, z=-1026.50], EntitySpider['Spider'/170632, l='MpServer', x=4821.59, y=44.00, z=-1001.28], EntityZombie['Zombie'/170639, l='MpServer', x=4799.50, y=68.00, z=-1102.50], EntityItem['item.item.chocoboFeather'/167570, l='MpServer', x=4827.38, y=62.13, z=-976.25], EntityZombie['Zombie'/169746, l='MpServer', x=4760.06, y=21.00, z=-989.59], EntityChocoboYellow['Yellow Chocobo'/169747, l='MpServer', x=4780.94, y=73.00, z=-1097.69], EntityZombie['Zombie'/18, l='MpServer', x=4813.30, y=36.00, z=-1025.70], EntityClientPlayerMP['Ipiano'/170164, l='MpServer', x=4785.77, y=62.62, z=-1038.91], EntityZombie['Zombie'/660, l='MpServer', x=4804.30, y=36.00, z=-1026.70], EntityPig['Pig'/169879, l='MpServer', x=4836.75, y=71.00, z=-1103.50], EntityZombie['Zombie'/662, l='MpServer', x=4788.30, y=36.00, z=-1032.70], EntityCreeper['Creeper'/169754, l='MpServer', x=4863.50, y=66.00, z=-976.50], EntityPig['Pig'/169764, l='MpServer', x=4823.53, y=63.00, z=-974.66], EntityCaveSpider['Cave Spider'/2095, l='MpServer', x=-16.77, y=-40.62, z=20.91], EntityCreeper['Creeper'/170290, l='MpServer', x=4843.50, y=26.00, z=-1064.50], EntityBat['Bat'/170551, l='MpServer', x=4746.41, y=12.89, z=-1097.25], EntityBat['Bat'/170552, l='MpServer', x=4735.53, y=13.64, z=-1099.69], EntityTrail['unknown'/961, l='MpServer', x=4785.77, y=62.62, z=-1038.91], EntityZombie['Zombie'/170948, l='MpServer', x=4766.50, y=18.00, z=-1062.50], EntityCaveSpider['Cave Spider'/1994, l='MpServer', x=-16.77, y=-26.62, z=0.91], EntityCreeper['Creeper'/170828, l='MpServer', x=4706.50, y=36.00, z=-1116.50], EntitySkeleton['Skeleton'/170835, l='MpServer', x=4707.59, y=36.00, z=-1110.78], EntitySkeleton['Skeleton'/170833, l='MpServer', x=4707.38, y=36.00, z=-1107.84], EntitySkeleton['Skeleton'/170210, l='MpServer', x=4776.97, y=63.00, z=-959.56], EntitySkeleton['Skeleton'/170594, l='MpServer', x=4855.50, y=69.00, z=-1089.50], EntityEnderman['Enderman'/170208, l='MpServer', x=4746.44, y=68.00, z=-981.72], EntitySkeleton['Skeleton'/170209, l='MpServer', x=4749.56, y=67.00, z=-979.56], EntityCreeper['Creeper'/169830, l='MpServer', x=4749.50, y=64.00, z=-1000.50], EntityPig['Pig'/170215, l='MpServer', x=4837.44, y=73.00, z=-1112.88], EntityPig['Pig'/170212, l='MpServer', x=4827.25, y=73.00, z=-1115.22], EntitySkeleton['Skeleton'/170596, l='MpServer', x=4854.50, y=69.00, z=-1087.50], EntityPig['Pig'/170213, l='MpServer', x=4861.78, y=70.00, z=-1088.91], EntityCreeper['Creeper'/171242, l='MpServer', x=4808.50, y=19.00, z=-1006.50], EntityZombie['Zombie'/169835, l='MpServer', x=4854.34, y=60.00, z=-966.13], EntityChocoboYellow['Yellow Chocobo'/746, l='MpServer', x=4828.31, y=63.00, z=-976.75], EntityBat['Bat'/170607, l='MpServer', x=4745.34, y=20.20, z=-998.88], EntityBat['Bat'/171500, l='MpServer', x=4719.66, y=14.26, z=-1088.75], EntityHorse['Horse'/751, l='MpServer', x=4843.41, y=68.00, z=-1075.72], EntitySpider['Spider'/170614, l='MpServer', x=4740.50, y=12.00, z=-1094.50], EntitySkeleton['Skeleton'/170615, l='MpServer', x=4740.50, y=12.17, z=-1094.50], EntityPig['Pig'/170231, l='MpServer', x=4762.69, y=49.00, z=-1115.50], EntitySpider['Spider'/170612, l='MpServer', x=4741.50, y=12.00, z=-1096.50], EntitySkeleton['Skeleton'/170234, l='MpServer', x=4719.69, y=64.00, z=-970.56], EntityZombie['Zombie'/169850, l='MpServer', x=4786.50, y=46.00, z=-967.50], EntitySpider['Spider'/170235, l='MpServer', x=4718.28, y=64.00, z=-970.03], EntityPig['Pig'/170236, l='MpServer', x=4714.16, y=71.00, z=-1097.47]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Unknown Source)
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 717645456 bytes (684 MB) / 1312317440 bytes (1251 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.141.1403 Minecraft Forge 10.13.3.1403 Optifine OptiFine_1.7.10_HD_U_B7 97 mods loaded, 97 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.141.1403} [Forge Mod Loader](forge-1.7.10-10.13.3.1403-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.3.1403} [Minecraft Forge](forge-1.7.10-10.13.3.1403-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AM2-Preloader{0.0.2} [AMCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{1.0.4.35} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.0.4.90} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    arsmagica2{1.4.0.008} [Ars Magica 2](1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Artifacts{1.1.1} [Artifacts](Artifacts-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    asielib{0.3.8} [asielib](AsieLib-1.7.10-0.3.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    atum{0.6} [Atum](Atum-1.7.10-0.6.60.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waila{1.5.8} [Waila](Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Automagy{0.23} [Automagy](Automagy-1.7.10-0.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    iChunUtil{4.1.3} [iChunUtil](iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BackTools{4.0.0} [BackTools](BackTools-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BattleTowers{1.5.1} [Battle Towers](BattleTowers-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioCraft{1.9.2} [BiblioCraft](BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.2-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Botania{r1.6-188} [Botania](Botania r1.6-188.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CarpentersBlocks{3.3.5} [Carpenter's Blocks](Carpenters Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ChickenChunks{1.3.4.17} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.1.1.323} [Forge Multipart](ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TwilightForest{2.3.5} [The Twilight Forest](twilightforest-1.7.10-2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    chisel{2.3.9.94} [Chisel 2](Chisel2_DEV-2.3.9.94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    chococraft{4.1.5} [Clienthax's ChocoCraft](ChocoCraft-4.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    colourfulportalsmod{1.4.2} [Colourful Portals](ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CosmeticArmor{1.0.5} [Cosmetic Armor](CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DragonMounts{r41-1.7.10} [Dragon Mounts](DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    dungeonpack{1.7.10-1.0} [Dungeon Pack](dungeonpack-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtrabiomesXL{3.16.0} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FastCraft{1.19} [FastCraft](fastcraft-1.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForbiddenMagic{1.7.10-0.561} [Forbidden Magic](Forbidden Magic-1.7.10-0.561.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forestry{3.4.0.7} [Forestry for Minecraft](forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.1.1.323} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    fossil{1.7.10 Build 7.0.1} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    foxlib{1.7.10-0.7.0} [FoxLib](FoxLib-1.7.10-0.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GardenCore{1.7.10-1.4.0} [Garden Core](GardenStuff-1.7.10-1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GardenContainers{1.7.10-1.4.0} [Garden Containers](GardenStuff-1.7.10-1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GardenStuff{1.7.10-1.4.0} [Garden Stuff](GardenStuff-1.7.10-1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GardenTrees{1.7.10-1.4.0} [Garden Trees](GardenStuff-1.7.10-1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GraveStone{2.12.2} [GraveStone](GraveStone-2.12.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inpure|core{1.7.10R1.0.0B9} [INpureCore](INpureCore-[1.7.10]1.0.0B9-54.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    journeymap{5.0.1} [JourneyMap](JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops](magicalcrops-4.0.0_PUBLIC_BETA_3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct](TConstruct-1.7.10-1.8.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MagicBees{1.7.10-2.1.22} [Magic Bees](magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    meteors{2.14.2} [Falling Meteors](meteors-1.7.10-2.14.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MobDismemberment{4.0.0} [MobDismemberment](MobDismemberment-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    cfm{3.4.7} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons{1.12.8.29} [NEI Addons](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|AppEng{1.12.8.29} [NEI Addons: Applied Energistics 2](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|Botany{1.12.8.29} [NEI Addons: Botany](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|Forestry{1.12.8.29} [NEI Addons: Forestry](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|CraftingTables{1.12.8.29} [NEI Addons: Crafting Tables](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|ExNihilo{1.12.8.29} [NEI Addons: Ex Nihilo](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    neiintegration{1.0.7} [NEI Integration](NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    desertcraft{1.7.2b} [Pam's DesertCraft](Pams DesertCraft 1.7.10a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    harvestcraft{1.7.10d} [Pam's HarvestCraft](Pams HarvestCraft 1.7.10f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    xreliquary{1.2} [Reliquary](Reliquary-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Roguelike{1.3.6.3} [Roguelike Dungeons](roguelike-1.7.10-1.3.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AS_Ruins{14.7} [Ruins Spawning System](Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    runicdungeons{1.0.6b} [Runic Dungeons](runicdungeons-1.0.6b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Sanguimancy{1.1.8} [Sanguimancy](Sanguimancy-1.7.10-1.1.8-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    secretroomsmod{4.7.1} [The SecretRoomsMod](secretroomsmod-1.7.10-4.7.1.413.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    soundfilters{0.8_for_1.7.X} [Sound Filters](SoundFilters-0.8_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SSR{rc3} [Soul Shards Reborn](SSR-rc3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    statues{2.1.4} [Statues](statues-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    StorageDrawers{1.7.10-1.2.4} [Storage Drawers](StorageDrawers-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    erebus{0.2pre12} [Erebus](TheErebus-0.2pre12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TrailMix{4.0.0} [TrailMix](TrailMix-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    VillagersNose{1.3a} [Villager's Nose](VillagersNose-1.7.10-1.3c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    warpbook{2.0.null} [Warp Book](warpbook-1.7.10_2.0.36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    wildcaves3{1.7.10} [Wild Caves 3](WildCaves3-0.4.3.7%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.1.1.323} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore: -[1.7.10]3.0.2-262
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
Info: The following plugins have been disabled in the config: equivelent.exchange
    Launched Version: 1.7.10-Forge10.13.3.1403-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 7700 Series GL version 4.4.13283 Compatibility Profile Context 14.501.1003.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (4)
```

**Comment by lumien231** [comment]
1.7.10 is no longer getting releases (unless major bugs come up)
