### ISSUE TITLE
randomthings.block.BlockBeanStalk server Crash

### ISSUE THREAD

**Issue by IchigoGames** [lumien231/Random-Things#72]
server crashing when some one was trying to grow magic beans heres server log and crash report 
https://www.dropbox.com/s/64lacrmi0ypem1r/fml-server-latest.log?dl=0
https://www.dropbox.com/s/odzz31fc1q1c2ro/crash-2016-04-23_17.20.06-server.txt?dl=0

**Comment by lumien231** [comment]
#70
