### ISSUE TITLE
[Compatibility]TooMuchTime

### ISSUE THREAD

**Issue by ElvenChaos** [lumien231/Random-Things#74]
The Bloodmoon feature works on odd times when used alongside the TooMuchTime mod to alter day/night times.
I know you have ended updates to 1.7.10, but would you add the ability to adjust what RT uses for day ticks and night ticks? Example: Day = 36000 ticks (3x day) Night = 12000 ticks (1x night).

Also, if TMT updates, would you include this compatibility for 1.8.9 and 1.9 on Bloodmoon (mod)?

Thank you for your time!

**Comment by lumien231** [comment]
If TMT updates i will add compability to the Bloodmoon mod, but i'm not going to touch 1.7.10 again. Sorry :(
