### ISSUE TITLE
[Feature Request] A BUD Block

### ISSUE THREAD

**Issue by Nallek** [lumien231/Random-Things#76]
I know it's supposedly planned for future MC updates, but it'd be great to have something working sooner. The block would output a pulse when a block updates near it (within x radius, or adjacent to a specific face, etc).

**Comment by Gunner76th** [comment]
I know Extra Utilities has this as well as an advanced BUD as one of their blocks in 1.7.10. Have you checked to see if it already exists in 1.10.2? I only mention this because Extra Utilities is a sudo default mod that has been in the majority of mod packs since 1.6.4

**Comment by lumien231** [comment]
Added to Vanilla
