### ISSUE TITLE
[1.8.9] Dyeing Machine, Missing Models/Textures

### ISSUE THREAD

**Issue by Rendarin** [lumien231/Random-Things#78]
I tried dyeing my iron armor set black, and then grey. Both sets end up looking like the screenshot below. I'm am running a personal modpack on Forge 11.15.1.1808. I am also running OptiFine 1.8.9 HD U H3. My skin is the Steve format, not the Alex format.

![2016-05-26_23 36 28](https://cloud.githubusercontent.com/assets/19583345/15597420/be2e9c32-239d-11e6-99ce-16c493c9aa50.png)

**Comment by lumien231** [comment]
This is not an issue anymore in the 1.9.4 version and i don't update older versions of Random Things, sorry.

**Comment by Overka38** [comment]
did you solve the problem because i have the same
