### ISSUE TITLE
[feature suggestion] gold and diamond anvils

### ISSUE THREAD

**Issue by 0Navis0** [lumien231/Random-Things#79]
I came with this idea when I saw this mod wich looked pretty nice http://minecraft.curseforge.com/projects/more-anvils
The idea of the gold and diamond anvils with have bigger durabilitie and need less level for repairing the tool. I think that this ideas fits well with the rest of the mod content.

**Comment by lumien231** [comment]
Don't really like it, seems a bit "bland". Kinda like different "tiers" of vanilla furnaces that just smelt faster / use less fuel. Especially because More Anvils pretty much already does this.
