### ISSUE TITLE
1.9-3.7 crashes client when slime is placed in crafting grid upper left corner

### ISSUE THREAD

**Issue by kreezxil** [lumien231/Random-Things#80]
In my mega pack for 1.9, after this was reported to me, I went through all of my mods loading them one by one and found that it is your mod that is causing this.

http://paste.ee/p/sZIyw

It is an index out of bounds error.

However, with just  your mod loaded I'm not having the issue, so it looks like it is conflicting with another mod but the crash report gives me no clue. Any clue/ideas?

**Comment by lumien231** [comment]
Unless you tell me with which mod this happens i have no clue sorry.
