### ISSUE TITLE
Fertilized dirt changes back to dirt

### ISSUE THREAD

**Issue by jeridan** [lumien231/Random-Things#83]
Fertilized dirt will revert to normal dirt when growing saplings.  It appears random, I have seen it turn after one tree and I have seen it take 10 trees to change.  

Using RandomThings-MC1.9-3.7

![2016-06-04_21 44 47](https://cloud.githubusercontent.com/assets/5779504/15803544/cfa99b26-2aa8-11e6-86c9-875725d4e1e6.png)
![2016-06-04_21 44 50](https://cloud.githubusercontent.com/assets/5779504/15803545/d2a6f896-2aa8-11e6-80b0-edab6efcb2d5.png)
![2016-06-04_21 47 23](https://cloud.githubusercontent.com/assets/5779504/15803546/d43b5ab2-2aa8-11e6-839c-5e46eee6067a.png)
![2016-06-04_21 50 21](https://cloud.githubusercontent.com/assets/5779504/15803547/d63889a2-2aa8-11e6-859c-e55a9095e841.png)

**Comment by lumien231** [comment]
So did you check whether this also happens in 1.9.4?

**Comment by jeridan** [comment]
Would appear that it does.  Using RandomThings-MC1.9.4-3.7.3

![2016-06-05_13 48 49](https://cloud.githubusercontent.com/assets/5779504/15807469/b54ee6a6-2b24-11e6-88f1-861bad131244.png)
![2016-06-05_13 48 56](https://cloud.githubusercontent.com/assets/5779504/15807470/b793fa96-2b24-11e6-8195-e0d2b2fe6324.png)
![2016-06-05_13 49 30](https://cloud.githubusercontent.com/assets/5779504/15807473/bc207c42-2b24-11e6-82c3-ee2c91b8a172.png)

**Comment by TheOldOne822** [comment]
It's a forge bug https://github.com/MinecraftForge/MinecraftForge/issues/2866
