### ISSUE TITLE
Lapis Lamp bug?

### ISSUE THREAD

**Issue by Reyls** [lumien231/Random-Things#86]
ver. 2.2.1
single player

after loading the world the lapis lamp doesnt emit any light
until it gets a click or sometime just the near of the player.
https://www.youtube.com/watch?v=Rp1b-XJ8PLE

**Comment by lumien231** [comment]
Ok this is at least semi fixed, they should now reliable turn on at least when a player is somewhere around them (Not as close as it was necessary before). I don't think i can make them turn on when a player is far away.
