### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid dimension id -343800852

### ISSUE THREAD

**Issue by MechaJ** [lumien231/Random-Things#88]
http://pastebin.ca/3632614

[update: taking out Anti-ID Conflict mod allows client to load, although a config option for spectre dim ID might be good idea anyways]

**Comment by lumien231** [comment]
Dimension IDs can be Integer now, i assume that mod has to update to that. The ID for the Spectre Dimension is -343800852, i highly doubt something will ever conflict with it^^.
