### ISSUE TITLE
Tried breaking cobblestone with the Block Breaker

### ISSUE THREAD

**Issue by bubblesayoyo** [lumien231/Random-Things#92]
[fml-server-3.txt](https://github.com/lumien231/Random-Things/files/332112/fml-server-3.txt)

**Comment by lumien231** [comment]
Will talk to the dev of FTB Utilities

**Comment by cri5ti** [comment]
Here's the issue on FTB Utilities:
https://github.com/LatvianModder/FTBUtilities/issues/145

**Comment by cri5ti** [comment]
@lumien231, I've had a quick glance over your code regarding the fakePlayer.
I see you're using a `WeakReference` on the player, is it possible it gets garbage collected after some time and after some time when it tries to break a block it is null?

Update: maybe not:

```
if (fakePlayer.get() != null)
{
    fakePlayer.get().interactionManager.tryHarvestBlock(targetPos);
}
```
