### ISSUE TITLE
Magnetic force: Crash when TPing to someone who's in Thaumcraft's bedrock dimension

### ISSUE THREAD

**Issue by Wyvern67** [lumien231/Random-Things#95]
I'm sorry, I don't have a crash log as this bug happened on a server that isn't mine.
Basically the server timed out when I teleported to someone who was in Thaumcraft's bedrock dimension and I was in the overworld.
The various animations and yellow runes didn't appear around me.

Various informations on the bedrock dimension:
http://ftbwiki.org/Awakened_Ichorium_Pickaxe
http://ftbwiki.org/Bedrock_Portal

**Comment by lumien231** [comment]
If you can't reproduce it / can't give me a crash log i can't fix it :P.

**Comment by ceselegend** [comment]
A complete crash report can be found here : http://pastebin.com/4bymQ7FY

It may not be related with Thaumic Tinkerer, we will try to reproduce it.
