### ISSUE TITLE
[1.9.4] Spirit invulnerability MP

### ISSUE THREAD

**Issue by LimeTheOn** [lumien231/Random-Things#96]
Hello I've tested our modpack in SP and i was able to kill a spirit but since we put it on the server Ive tried to kill multiple spirits and all of them were invulnerable.
fml 1987
RT 373

**Comment by lumien231** [comment]
I assume you tried to kill them with potions?

Wiki: "Spirits can not be harmed by physical attacks (An exception being the Spectre Sword), they are incorporeal after all. You will have to use magic to kill them (_cough_ potions _cough_)"

**Comment by LimeTheOn** [comment]
but but but in sp i swear i killed it with a sword o.O more specificly either a tinkers cleaver or a weaponsplus lava sword.I know for sure because i was testing stuff on the copy of the server. Does it matter that i was in the nether when i was able to kill it?

**Comment by LimeTheOn** [comment]
Even more specificly, we have Levels and my lava sword might be leveled up with abilities mimicing potion effects, so is it possible that way?

**Comment by LimeTheOn** [comment]
Nevermind WeaponsPlus just bypasses your invulnerablitiy that confused me, @sokratis12GR will be sooo happy that im bringing him another thing to fix right after he updated :D

**Comment by sokratis12GR** [comment]
WeaponsPlus bypass the invulnerability because the weapons actually apply potion effect on the entity

**Comment by LimeTheOn** [comment]
Ok, so consider it a feature? :D

**Comment by sokratis12GR** [comment]
It is of course intended. @lumien231 You can close the Issue

**Comment by lumien231** [comment]
Magical Swords.
