### ISSUE TITLE
Notification Interface incompatible with current version of OC due to outdated API

### ISSUE THREAD

**Issue by Kodos-Atoz** [lumien231/Random-Things#96]
OpenComputers is on 1.4.5 currently, and whenever I hook up a notification interface to a computer, it causes the computer to constantly error until I remove it.  I'm opening this issue in hopes that the API can be updated and I can use the Notification Interface for a few programs I'm working on that will allow remote alerts to a player when various conditions are met.

**Comment by lumien231** [comment]
https://github.com/lumien231/Random-Things/commit/554127b52f7622127d27564446db203931409462
