### ISSUE TITLE
Crash when opening video settings

### ISSUE THREAD

**Issue by XBlackLeopardX** [lumien231/Random-Things#97]
While working on my modpack i noticed a bug which caused me to crash whenever i try to go to video settings, which i have traced back to random things and optifine

im using the lastest version of random things and optifine
not sure whether this is something you can fix or if its just optifine related but thought i should report it either way
crash http://pastebin.com/SXk4t0VB

**Comment by lumien231** [comment]
Pretty sure thats optifine, report it there pls.

**Comment by XBlackLeopardX** [comment]
okay no problem

**Comment by lumien231** [comment]
I've messaged him about this bug when it was first reported, didn't get an answer and i can't fix that.

**Comment by XBlackLeopardX** [comment]
i mesaged him and let him know and he replyed with this and i did just remember that i also have the gammabright disabled so no one can change it in game thats what was causing it http://prntscr.com/5uej9s

**Comment by lumien231** [comment]
Well yes, i know that that feature is the issue :P. Glad to hear he will fix it.
