### ISSUE TITLE
Block Breaker crashes server

### ISSUE THREAD

**Issue by pathways029** [lumien231/Random-Things#97]
Whitelisted server running on Donutcraft 1.9.4. Placing a block in front of a block Breaker causes server crash. Repeatable.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-54.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  IC2core (industrialcraft-2-2.5.45-ex19.jar)
  LoadingPlugin (Quark-beta-28.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 7/2/16 11:47 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:51)
    at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9)
    at net.minecraft.server.management.UserList.func_152683_b(SourceFile:68)
    at net.minecraft.server.management.UserListOps.func_187452_a(SourceFile:30)
    at com.feed_the_beast.ftbl.util.FTBLib.isOP(FTBLib.java:318)
    at com.feed_the_beast.ftbl.api.permissions.rankconfig.RankConfig.getJson(RankConfig.java:50)
    at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onBlockBreak(FTBUPlayerEventHandler.java:297)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_224_FTBUPlayerEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:697)
    at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:286)
    at lumien.randomthings.tileentity.TileEntityBlockBreaker.func_73660_a(TileEntityBlockBreaker.java:96)
    at net.minecraft.world.World.func_72939_s(World.java:1797)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
    at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:51)
    at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9)
    at net.minecraft.server.management.UserList.func_152683_b(SourceFile:68)
    at net.minecraft.server.management.UserListOps.func_187452_a(SourceFile:30)
    at com.feed_the_beast.ftbl.util.FTBLib.isOP(FTBLib.java:318)
    at com.feed_the_beast.ftbl.api.permissions.rankconfig.RankConfig.getJson(RankConfig.java:50)
    at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onBlockBreak(FTBUPlayerEventHandler.java:297)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_224_FTBUPlayerEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:697)
    at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:286)
    at lumien.randomthings.tileentity.TileEntityBlockBreaker.func_73660_a(TileEntityBlockBreaker.java:96)

-- Block entity being ticked --
Details:
    Name: randomthings:blockBreaker // lumien.randomthings.tileentity.TileEntityBlockBreaker
    Block type: ID #1704 (tile.blockBreaker // lumien.randomthings.block.BlockBlockBreaker)
    Block data value: 5 / 0x5 / 0b0101
    Block location: World: (-149,78,1157), Chunk: (at 11,4,5 in -10,72; contains blocks -160,0,1152 to -145,255,1167), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
    Actual block type: ID #1704 (tile.blockBreaker // lumien.randomthings.block.BlockBlockBreaker)
    Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1797)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
    Level name: world
    All players: 2 total; [EntityPlayerMP['Frozenjax'/21887, l='world', x=-77.38, y=57.00, z=1017.50], EntityPlayerMP['PathMaker'/179803, l='world', x=-146.06, y=78.00, z=1159.44]]
    Chunk stats: ServerChunkCache: 733 Drop: 0
    Level seed: 65112893
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: Cindy
    Level spawn location: World: (-120,69,1224), Chunk: (at 8,4,8 in -8,76; contains blocks -128,0,1216 to -113,255,1231), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
    Level time: 13212840 game time, 769682 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 23601 (now: false), thunder time: 12736 (now: true)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Linux (amd64) version 3.13.0-87-generic
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 548386736 bytes (522 MB) / 1151090688 bytes (1097 MB) up to 4225236992 bytes (4029 MB)
    JVM Flags: 4 total; -Xmx4096M -Xms128M -XX:MaxMetaspaceSize=256M -XX:+UseConcMarkSweepGC
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
    FML: MCP 9.28 Powered by Forge 12.17.0.1966 64 mods loaded, 64 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1966-universal.jar) 
    UCHIJAAAA   Forge{12.17.0.1966} [Minecraft Forge](forge-1.9.4-12.17.0.1966-universal.jar) 
    UCHIJAAAA   actuallyadditions{1.9.4-r45} [Actually Additions](ActuallyAdditions-1.9.4-r45.jar) 
    UCHIJAAAA   autopackager{1.6.3} [AutoPackager](autopackager-1.6.3.jar) 
    UCHIJAAAA   bagginses{2.4.2d} [Bagginses](Bagginses-1.9.4-2.4.2d.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   bdlib{1.11.0.1} [BD Lib](bdlib-1.11.0.1-mc1.9.4.jar) 
    UCHIJAAAA   BiomesOPlenty{4.1.0.2029} [Biomes O' Plenty](BiomesOPlenty-1.9.4-4.1.0.2029-universal.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.9.4-alpha-1.0.0a.jar) 
    UCHIJAAAA   JEI{3.6.7.216} [Just Enough Items](jei_1.9.4-3.6.7.216.jar) 
    UCHIJAAAA   BloodMagic{1.9.4-2.0.1-44} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.1-44.jar) 
    UCHIJAAAA   Chameleon{1.9-2.1.4} [Chameleon](Chameleon-1.9-2.1.4.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel](Chisel-MC1.9.4-0.0.5.27.jar) 
    UCHIJAAAA   chiselsandbits{10.7} [Chisels & Bits](chiselsandbits-10.7.jar) 
    UCHIJAAAA   cyclopscore{0.6.3} [Cyclops Core](CyclopsCore-1.9.4-0.6.3.jar) 
    UCHIJAAAA   ElecCore{1.5.292} [ElecCore](ElecCore-1.9.4-1.5.292.jar) 
    UCHIJAAAA   deepresonance{1.2.0beta34} [DeepResonance](deepresonance-1.9.4-1.2.0beta34.jar) 
    UCHIJAAAA   endercore{1.9.4-0.4.0.26-alpha} [EnderCore](EnderCore-1.9.4-0.4.0.26-alpha.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   EnderIO{1.9.4-3.0.0.43_alpha} [Ender IO](EnderIO-1.9.4-3.0.0.43_alpha.jar) 
    UCHIJAAAA   shetiphiancore{3.2.6} [ShetiPhian-Core](shetiphiancore-1.9.4-3.2.6.jar) 
    UCHIJAAAA   endertanks{1.3.5} [EnderTanks](endertanks-1.9.4-1.3.5.jar) 
    UCHIJAAAA   evilcraft{0.10.2} [EvilCraft](EvilCraft-1.9.4-0.10.2.jar) 
    UCHIJAAAA   FFS{1.9.4-1.6.3-b23} [Fancy Fluid Storage](Fancy Fluid Storage-1.9.4-1.6.3-b23.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.9.4-v3.1} [Flat Colored Blocks](flatcoloredblocks-mc1.9.4-v3.1.jar) 
    UCHIJAAAA   IC2{2.5.45-ex19} [IndustrialCraft 2](industrialcraft-2-2.5.45-ex19.jar) 
    UCHIJAAAA   forestry{5.0.20.167} [Forestry](forestry_1.9.4-5.0.20.167.jar) 
    UCHIJAAAA   ftbl{2.1.0} [FTBLib](FTBLib-1.9.4-2.1.0-pre1.jar) 
    UCHIJAAAA   ftbu{2.1.0} [FTBUtilities](FTBUtilities-1.9.4-2.1.0-pre1.jar) 
    UCHIJAAAA   advgenerators{0.9.20.1} [Advanced Generators](generators-0.9.20.1-mc1.9.4.jar) 
    UCHIJAAAA   gravestone{1.3.0} [Gravestone](Gravestone Mod 1.3.0.jar) 
    UCHIJAAAA   inventorytweaks{1.61-beta-54-009e843} [Inventory Tweaks](InventoryTweaks-1.61-beta-54.jar) 
    UCHIJAAAA   IronChest{6.0.145.787} [Iron Chest](ironchest-1.9.4-6.0.145.787.jar) 
    UCHIJAAAA   mantle{1.9.4-0.10.2.jenkins149} [Mantle](Mantle-1.9.4-0.10.2.jar) 
    UCHIJAAAA   testdummy{1.10} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.11.jar) 
    UCHIJAAAA   Morpheus{1.9.4-3.1.5} [Morpheus](Morpheus-1.9.4-3.1.5.jar) 
    UCHIJAAAA   harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4b.jar) 
    UCHIJAAAA   progressiveautomation{1.6.46} [Progressive Automation](ProgressiveAutomation-1.9.4-1.6.46.jar) 
    UCHIJAAAA   Psi{r1.0-35} [Psi](Psi-r1.0-35.jar) 
    UCHIJAAAA   quantumflux{2.0.7} [QuantumFlux](quantumflux-1.9.4-2.0.7.jar) 
    UCHIJAAAA   reborncore{2.5.4.47} [RebornCore](RebornCore-1.9.4-2.5.4.47-universal.jar) 
    UCHIJAAAA   QuantumStorage{3.1.0} [QuantumStorage](QuantumStorage-1.9.4-3.1.0.jar) 
    UCHIJAAAA   Quark{beta-28} [Quark](Quark-beta-28.jar) 
    UCHIJAAAA   randomthings{3.7.3} [Random Things](RandomThings-MC1.9.4-3.7.3.jar) 
    UCHIJAAAA   reborncore-mcmultipart{2.5.4.47} [reborncore-MCMultiPart](RebornCore-1.9.4-2.5.4.47-universal.jar) 
    UCHIJAAAA   StorageDrawers{1.9-3.1.8} [Storage Drawers](StorageDrawers-1.9-3.1.8.jar) 
    UCHIJAAAA   refinedstorage{0.7.16} [Refined Storage](refinedstorage-0.7.16.jar) 
    UCHIJAAAA   xreliquary{1.9.4-1.3.2.390} [Reliquary](Reliquary-1.9.4-1.3.2.390.jar) 
    UCHIJAAAA   rftools{4.64} [RFTools](rftools-1.9.4-4.64.jar) 
    UCHIJAAAA   rftoolsdim{4.30beta42} [RFTools Dimensions](rftoolsdim-1.9.4-4.30beta42.jar) 
    UCHIJAAAA   roots{0.1} [Roots](roots-0.005.jar) 
    UCHIJAAAA   runesofwizardry{1.9.4-0.6.7} [Runes of Wizardry](Runes-of-Wizardry-1.9.4-0.6.7.jar) 
    UCHIJAAAA   runesofwizardry_classics{1.9.4-0.3.4} [Runes of Wizardry - Classic Dusts Pack](RunesofWizardry-Classics-1.9.4-0.3.4.jar) 
    UCHIJAAAA   Signals{1.0} [Signals](Signals-1.9.4-0.1.2-universal.jar) 
    UCHIJAAAA   simpleretrogen{3.0.1+6} [Simple Retrogen](simpleretrogen-1.9.4-3.0.16.jar) 
    UCHIJAAAA   soulshardstow{1.9.4-2.4.4-32} [Soul Shards - The Old Ways](SoulShards-TOW-1.9.4-2.4.4-32.jar) 
    UCHIJAAAA   tconstruct{1.9.4-2.3.2.jenkins255} [Tinkers' Construct](TConstruct-1.9.4-2.3.2.jar) 
    UCHIJAAAA   techreborn{1.3.2.120} [TechReborn](TechReborn-1.9.4-1.3.2.120-universal.jar) 
    UCHIJAAAA   theoneprobe{1.0.10} [The One Probe](theoneprobe-1.9.4-1.0.10.jar) 
    UCHIJAAAA   totemic{1.9.4-0.7.5} [Totemic](Totemic-1.9.4-0.7.5.jar) 
    UCHIJAAAA   ICSE{1.0.0.0} [I Can See Everything](Wawla-1.9.4-2.2.1.192.jar) 
    UCHIJAAAA   wawla{2.2.1.188} [What Are We Looking At](Wawla-1.9.4-2.2.1.192.jar) 
    UCHIJAAAA   Zoology{1.0} [Zoology](zoology-1.9.4-alpha-1.1.0.jar) 
    Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
FMLPlugin (InventoryTweaks-1.61-beta-54.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  shetiphian.core.asm.ClassTransformer
IC2core (industrialcraft-2-2.5.45-ex19.jar)

LoadingPlugin (Quark-beta-28.jar)
  vazkii.quark.base.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

```
List of loaded APIs: 
    * actuallyadditionsapi (17) from ActuallyAdditions-1.9.4-r45.jar
    * Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
    * BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.0.1-44.jar
    * ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.5.27.jar
    * ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.5.27.jar
    * ChiselsAndBitsAPI (1.8.1) from chiselsandbits-10.7.jar
    * CoFHAPI (1.8.9R1.2.0B1) from EnderIO-1.9.4-3.0.0.43_alpha.jar
    * CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from mcjtylib-1.9.4-1.9.1.jar
    * CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
    * DR-API (1.0.4-Beta) from deepresonance-1.9.4-1.2.0beta34.jar
    * ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.292.jar
    * EnderIOAPI (0.0.2) from EnderIO-1.9.4-3.0.0.43_alpha.jar
    * EnderIOAPI|Redstone (0.0.2) from EnderIO-1.9.4-3.0.0.43_alpha.jar
    * EnderIOAPI|Teleport (0.0.2) from EnderIO-1.9.4-3.0.0.43_alpha.jar
    * EnderIOAPI|Tools (0.0.2) from EnderIO-1.9.4-3.0.0.43_alpha.jar
    * ForestryAPI|apiculture (4.8.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|arboriculture (4.2.1) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|circuits (3.1.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|core (5.0.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|farming (2.1.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|food (1.1.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|fuels (2.0.1) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|genetics (4.7.1) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|greenhouse (5.0.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|hives (4.1.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|lepidopterology (1.3.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|mail (3.0.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|multiblock (3.0.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|recipes (5.4.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|storage (3.0.0) from forestry_1.9.4-5.0.20.167.jar
    * ForestryAPI|world (2.1.0) from forestry_1.9.4-5.0.20.167.jar
    * IC2API (1.0) from industrialcraft-2-2.5.45-ex19.jar
    * jeresources|API (0.4.6.38) from JustEnoughResources-1.9.4-0.4.6.38.jar
    * JustEnoughItemsAPI (3.1.0) from jei_1.9.4-3.6.7.216.jar
    * McJtyLib (1.9.4-1.9.1) from mcjtylib-1.9.4-1.9.1.jar
    * PsiAPI (2) from Psi-r1.0-35.jar
    * reborncoreAPI (2.5.4.47) from RebornCore-1.9.4-2.5.4.47-universal.jar
    * SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.9.4-2.4.4-32.jar
    * StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
    * StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
    * StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
    * StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.8.jar
    * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.8.jar
    * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.8.jar
    * StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
    * StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
    * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
    * techrebornAPI (1.3.2.120) from TechReborn-1.9.4-1.3.2.120-universal.jar
    * totemic|API (1.0.0) from Totemic-1.9.4-0.7.5.jar
    * WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
EnderIO: No known problems detected.
Profiler Position: N/A (disabled)
Player Count: 2 / 15; [EntityPlayerMP['Frozenjax'/21887, l='world', x=-77.38, y=57.00, z=1017.50], EntityPlayerMP['PathMaker'/179803, l='world', x=-146.06, y=78.00, z=1159.44]]
Is Modded: Definitely; Server brand changed to 'fml,forge'
Type: Dedicated Server (map_server.txt)
```

**Comment by lumien231** [comment]
#92
