### ISSUE TITLE
energy distributors not outputing to anything but cap banks

### ISSUE THREAD

**Issue by kurokuno** [lumien231/Random-Things#99]
no machine seems to get power or even be seen by the block or the ender one however if you link them to an empty cap back they output just fine

**Comment by lumien231** [comment]
Screenshot of your setup please?

**Comment by kurokuno** [comment]
eeer i would however i did it in creative testing its honestly just an energy dist siting next to a line of like 5 pulverizes have also tried with sag mills from enderIO  the dist clearly had energy in it just would not output and the ender one i just used the target filter clearly showed the pulv highlighted put it in and did nothing
