### ISSUE TITLE
Redstone Remote does not work with Contact Lever/Button

### ISSUE THREAD

**Issue by Ruladian** [lumien231/Random-Things#99]
Not sure it is supposed to be this way or not but when using the Redstone Remote it does not effect the Contact Lever or Contact Button.  I have tried it with a linked location block in front of the Contacts and having the Contacts as the link location with the same result.

**Comment by lumien231** [comment]
I'm not sure how they are related? The Contact Lever & Button **emit** Redstone, they don't react to it.

**Comment by Ruladian** [comment]
My understanding was that the remote was like pushing a button at the linked location.  So I figured that if I used the remote on the block in front of the Contact Lever it would activate it so it would turn on or off the Redstone signal emitted by the Contact Lever.

**Comment by lumien231** [comment]
No when you press a button in the Redstone Remote the target will be powered by redstone for a second.
